Add missing "Open Git Bash" step
github/docs pull request #10376
Opened 2021-09-28 20:29 UTC by rcowsill

### Why:

Closes #10375

### What's being changed:

Added a missing step to the Atom setup instructions for Windows. All the other lists include the step of opening a terminal window, but it was missing for this one case.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

2021-09-28 20:46 UTC, Z-byte-prog approved these changes

2021-09-28 21:40 UTC, Z-byte-prog approved these changes

2021-09-28 21:41 UTC, Z-byte-prog approved these changes

2021-09-28 21:41 UTC, Z-byte-prog approved these changes

2021-09-28 21:43 UTC, Z-byte-prog approved these changes

2021-09-28 21:46 UTC, Z-byte-prog approved these changes

2021-09-28 21:46 UTC, Z-byte-prog approved these changes

2021-09-29 02:25 UTC, memet156 requested changes
Silin

2021-09-29 12:18 UTC, ramyaparimi commented
@rcowsill 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

2021-09-30 23:41 UTC, ethanpalm approved these changes
👋🏼  Thanks for creating this PR @rcowsill! Your change looks great and should definitely help people who are setting up Atom as their editor. I'll get this merged once all the checks are passing ✨ 

Thanks for taking the time to contribute to the GitHub docs!

2021-10-01 16:30 UTC, merged