chore: run autoupdate branch on cron schedule
github/docs pull request #1050
Opened 2020-11-04 00:43 UTC by nschonni

### Why:

### What's being changed:

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-11-05 23:20 UTC, janiceilene commented
Thank so much @nschonni! I'll get this triaged for review 🎉

2020-11-06 17:26 UTC, chiedo commented
@nschonni I'm a little unsure about making this change with the complexities of repo sync. But will dig into this more deeply when I or one of my team mates has more time!

2020-11-06 17:31 UTC, nschonni commented
OK, no worries

2020-11-12 21:28 UTC, N35708 requested changes
#1285 #143

2020-11-12 21:29 UTC, N35708 approved these changes
#1285 #143

2020-11-30 16:55 UTC, heiskr commented
I think given the potential here to break other workflows, we won't able to accept this change. Thank you though :)

2020-11-30 16:55 UTC, closed without merging

2020-12-10 19:29 UTC, chiedo commented
@nschonni thanks for the contribution! We ended up re-implementing this in a more isolated fashion.

https://github.com/github/docs/blob/main/.github/workflows/autoupdate-repo-sync-branch-on-cron.yml along with another label to let us isolate repo sync PRs. https://github.com/github/docs/blob/main/.github/workflows/repo-sync.yml#L55

Thanks again.