Juan felix Pena
github/docs pull request #1081
Opened 2020-11-04 22:20 UTC by luckyflex2702

### Why:

### What's being changed:

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-11-05 07:00 UTC, TomasFlow approved these changes

2020-11-05 07:16 UTC, SMAKSS reviewed
Looks like spam! 😶

2020-11-05 07:51 UTC, TomasFlow approved these changes

2020-11-05 08:10 UTC, Tizzit-max approved these changes

2020-11-05 08:12 UTC, Tizzit-max requested changes
Van we get a background check plz @dependabotrebase

2020-11-05 11:10 UTC, TomasFlow approved these changes

2020-11-05 11:10 UTC, TomasFlow approved these changes

2020-11-06 05:49 UTC, nafeef123 approved these changes

2020-11-06 21:25 UTC, closed without merging