Update dependabot metadata field
github/docs pull request #12139
Opened 2021-11-19 10:34 UTC by iamandrewluca

### Why:

Closes #12136

### What's being changed:

Change metadata field according to the docs

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-11-19 13:26 UTC, ramyaparimi commented
@iamandrewluca 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

2021-11-19 13:59 UTC, mchammer01 commented
👋🏻 - I'll take a look at this but will first check with the relevant team as my knowledge in this area is very limited. Thanks for your patience 🙂

2021-11-22 10:24 UTC, brrygrdn requested changes
Thanks for opening this PR, I think it's worth aligning both the project README and documentation like this 👍🏻 

We just need to ensure the `id` is updated as well.

2021-11-22 10:24 UTC, brrygrdn commented on content/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions.md
> +      #  - steps.dependabot-metadata.outputs.dependency-names
This line refers to the `id` of the previous step on line 182, which is called `metadata` in this example. In the [dependabot/fetch-metadata README](https://github.com/dependabot/fetch-metadata/blob/main/README.md?plain=1#L94) this step is called `dependabot-metadata` which is why the two examples have diverged.

I think being consistent and using `dependabot-metadata` in both places is worthwhile, but we should also update line 182.

2021-11-22 10:24 UTC, brrygrdn commented on content/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions.md
> +        if: ${{ steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
Same as above, line 217 should be `id: dependabot-metadata`

2021-11-22 10:24 UTC, brrygrdn commented on content/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions.md
> +        if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'my-dependency') && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
Line 280 as well

2021-11-22 10:36 UTC, mchammer01 commented
Thanks for the technical review @brrygrdn ✨ 
@iamandrewluca 👋🏻 - can you add @brrygrdn's suggestions to your PR, so I can give it a quick check and merge it? Thank you!

2021-11-22 18:11 UTC, iamandrewluca commented
@mchammer01 @brrygrdn updated the PR.

It seems that I configured my action wrong then
https://github.com/iamandrewluca/holiday-time/blob/e35e02a93cbef5e5dcad8efbd7965d33d203ad0a/.github/workflows/dependabot.yml#L19

It sems to work because of `!=`

2021-11-23 11:15 UTC, brrygrdn approved these changes
Thanks for the update, this looks good to me! :shipit:

2021-11-23 14:55 UTC, mchammer01 approved these changes
LGTM, thanks for applying the suggestions 🙇🏻 😃

2021-11-23 15:05 UTC, merged