Correct workflow badge 'event' example
github/docs pull request #12331
Opened 2021-11-25 09:15 UTC by danielfdickinson

### Why:

Closes https://github.com/github/docs/issues/12329

### What's being changed:

As described in issue #123129, Using a URL such as <https://github.com/github/docs/actions/workflows/main.yml/badge.svg?event=pull_request> shows no status, as with this badge: ![test-check-links PR](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?event=pull_request).

Changing it to a URL such as <https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request> shows the status of the event (in this case ``pull_request``) as shown with the following badge: ![test-check-links PR](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request).

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-11-25 09:21 UTC, D-rock93 reviewed
Help fix my so I can make $ plz

2021-11-29 14:15 UTC, ramyaparimi commented
@danielfdickinson 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

2021-12-08 19:09 UTC, ethomson requested changes

2021-12-08 19:09 UTC, ethomson commented on content/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge.md
> +## Using the `on` parameter
```suggestion
## Using the `event` parameter
```

2021-12-08 19:09 UTC, ethomson commented on content/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge.md
> +![example on parameter](https://github.com/github/docs/actions/workflows/main.yml/badge.svg?on=pull_request)
```suggestion
![example on parameter](https://github.com/github/docs/actions/workflows/main.yml/badge.svg?event=push)
```

2021-12-08 19:09 UTC, ethomson commented on content/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge.md
>  This Markdown example adds a badge that displays the status of workflow runs triggered by the `pull_request` event.
```suggestion
This Markdown example adds a badge that displays the status of continuous integration builds in your default branch; those are builds that are triggered by the `push` event (when a commit is pushed or when a pull request is merged) into the repository's default branch.
```

2021-12-08 19:10 UTC, ethomson commented
`event` is the correct parameter.  `on` is ignored, which means that:

`https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request`: 
![https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request)

is the equivalent of no parameter at all:
`https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg`:
![https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?on=pull_request)

because we ignore unknown parameters; so it's also the equivalent of a parameter like `foo`:
`https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?foo=pull_request`:
![https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?foo=pull_request](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?foo=pull_request)

Now to the question of why we are not showing you status for `event=pull_request`: because we default to the default branch when none is specified.  And your default branch has never been the source of a pull request.  If you add an explicit branch, now you'll see the status for that branch:

`https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?event=pull_request&branch=pr-upload-logs-on-failure`: ![https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?event=pull_request&branch=pr-upload-logs-on-failure](https://github.com/danielfdickinson/hugo-action-check-links/actions/workflows/test-check-links.yml/badge.svg?event=pull_request&branch=pr-upload-logs-on-failure)

(We do not have a way to show a badge for pull requests _targetting_ a branch, eg `target=main`.  If this would be useful to you [I'd love to understand more about it](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback).

But I think that what most people want for the status badge here is _not_ based on the `pull_request` trigger at all, but on the `push` trigger.  (In other words, _is my main branch CI green?)  And our documentation should reflect _that_.

2021-12-10 04:45 UTC, danielfdickinson commented
First, thank you for clarifying the on vs. event situation.

>But I think that what most people want for the status badge here is not based on the pull_request trigger at all, but on the push trigger. (In other words, _is my main branch CI green?) And our documentation should reflect that.

I guess I'm a little confused about how that differs from the default (no event) for a branch.

What I was hoping for, really, was that I could look at the badge in the README for a PR (for example if the README is deployed as part of the preview version of update docs) and see if the PR is CI green.

It's kind of corner case though, and I'll probably just drop using the event parameter in my own repos.

2021-12-19 14:28 UTC, danielfdickinson commented
I've add https://github.com/github/feedback/discussions/9091 for what I was actually looking for (as suggested by @ethomson). I'm not quite sure what to do with the PR since the changes needed are completely different than proposed (basically needs to be rewritten as a clarification of the current docs, with the information provided by @ethomson). That probably should be done a new/separate PR?

2021-12-20 14:42 UTC, hubwriter commented
> That probably should be done a new/separate PR?

Yes, I agree that it would be best to close this PR and raise a separate issue & PR for clarification of this area.

2021-12-20 14:42 UTC, closed without merging