Use a tag to refer to setup-swift action
github/docs pull request #12680
Opened 2021-12-06 10:50 UTC by fwal

### Why:

Closes #12678

### What's being changed:

I changed the version of the [fwal/setup-swift](https://github.com/marketplace/actions/setup-swift) Action to point to version tag `v1` instead.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-12-06 12:56 UTC, ramyaparimi commented
@fwal 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

2021-12-07 03:28 UTC, Claudio060320 reviewed
Duplicate of #

2021-12-08 18:27 UTC, ethomson commented
Hi @fwal - thanks for the PR.  We pin to SHAs for third-party actions, both in the [starter workflow templates](http://github.com/actions/starter-workflows) and the docs.  Can we PIN the to the current `v1` SHA in the docs instead of `@v1`?  Thanks!

2021-12-08 19:39 UTC, ethomson requested changes

2021-12-08 19:39 UTC, ethomson commented on content/actions/automating-builds-and-tests/building-and-testing-swift.md
> +      - uses: fwal/setup-swift@v1
```suggestion
      - uses: fwal/setup-swift@234ae35a6c75c32600301c1072285a33503c7a69
```

2021-12-08 19:39 UTC, ethomson commented on content/actions/automating-builds-and-tests/building-and-testing-swift.md
> +  - uses: fwal/setup-swift@v1
```suggestion
  - uses: fwal/setup-swift@234ae35a6c75c32600301c1072285a33503c7a69
```

2021-12-08 19:39 UTC, ethomson commented on content/actions/automating-builds-and-tests/building-and-testing-swift.md
> +  - uses: fwal/setup-swift@v1
```suggestion
  - uses: fwal/setup-swift@234ae35a6c75c32600301c1072285a33503c7a69
```

2021-12-09 01:40 UTC, Claudio060320 commented on content/actions/automating-builds-and-tests/building-and-testing-swift.md
> +      - uses: fwal/setup-swift@v1
```suggestion
      - uses: fwal/setup-swift@v1
```

2022-01-10 09:59 UTC, fwal commented
@ethomson Hi! Sure, pinned to latest version 1.11.0 🙂

2022-01-14 06:14 UTC, lucascosti approved these changes
Sorry for the delay, @fwal! This looks good (shas are the same as 1.11.0), so I'll merge this in. 🚀

2022-01-14 06:21 UTC, merged