Add the preface step as step 1 instead.
github/docs pull request #13686
Opened 2022-01-03 22:08 UTC by scott-lydon

### Why:

Closes [13683](https://github.com/github/docs/issues/13683) 

When I encounter this tutorial, my first reaction is "darn" they have a bunch of stuff for me to read before jumping into the steps that I can act on. I run a calculation, "are these paragraphs going to distract me and waste my time?" Or should I just jump into the steps.  I usually try to just jump in, to keep the momentum going.  So I look at step 1, and instead of it being the first step, it suggests copying the SSH but doesn't tell you where to get it. So its not really a first step at all.  Being that a requisite step needs to come before it.  So this is really a second step. This made me wonder, is the "how to add an SSH key hiding on another page?" This is when my frustration started to peak.  And this is the introduction to the docs and the kind of thing that makes me groan in fear and pain every time I have to refresh my SSH keys with GitHub.  

### What's being changed:

It shifts the "preface" to being the first step which would really clear up the confusion I get every time I encounter the docs. 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2022-01-04 14:45 UTC, ramyaparimi commented
@scott-lydon 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

2022-01-06 03:25 UTC, masumh reviewed
Please help me automatic adjust my problem

2022-01-06 03:26 UTC, masumh commented
Please help me

2022-01-06 03:26 UTC, masumh reviewed
Please help me

2022-01-06 04:07 UTC, masumh commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
> -* [Checked for existing SSH keys](/articles/checking-for-existing-ssh-keys)
Please help

2022-01-06 04:08 UTC, masumh reviewed
Please help

2022-01-06 04:08 UTC, masumh commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
> +1. [Check if you already have the SSH key you want to use](/articles/checking-for-existing-ssh-keys) and [generate a new SSH key and add it to the ssh-agent](/articles/generating-a-new-ssh-key-and-ad
Please help

2022-01-06 04:09 UTC, masumh reviewed
Please help

2022-01-06 04:10 UTC, masumh commented
> Please help

2022-01-29 21:17 UTC, Samuelgha commented
Please am a new here

2022-02-24 23:55 UTC, ethanpalm requested changes
Hi @scott-lydon, thanks for creating a PR and clearly explaining your process. ⚡ 

For procedural articles like this one, we put all the prerequisites and conceptual information before the actual procedure, not inside the procedural steps. The goal here is to make sure people have the right context for a procedure or that they've had the chance to see other articles that relate to the procedure that they're about to do.  You can see more about how we document prerequisites in the GitHub docs [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#procedural-steps) and [content model](https://github.com/github/docs/blob/main/contributing/content-model.md#prerequisites).

So, for this PR, I think we can highlight that these steps are prerequisites by adding a "Prerequisites" header and a header for the procedure itself.

After incorporating these changes, this PR should be ready to merge. Please let me know if you have any questions and thanks for taking the time to contribute to the GitHub docs! 🚀

2022-02-24 23:55 UTC, ethanpalm commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
```suggestion

## Prerequisites
Before adding a new SSH key to your account on {% ifversion ghae %}{% data variables.product.product_name %}{% else %}{% data variables.product.product_location %}{% endif %}, you should have:
* [Checked for existing SSH keys](/articles/checking-for-existing-ssh-keys)
* [Generated a new SSH key and added it to the ssh-agent](/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

After adding a new SSH key to your account on {% ifversion ghae %}{% data variables.product.product_name %}{% else %}{% data variables.product.product_location %}{% endif %}, you can reconfigure any local repositories to use SSH. For more information, see "[Switching remote URLs from HTTPS to SSH](/github/getting-started-with-github/managing-remote-repositories/#switching-remote-urls-from-https-to-ssh)."
```

This adds a header to more clearly label the prerequisites.

2022-02-24 23:55 UTC, ethanpalm commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
> +2. Copy the SSH public key to your clipboard.
```suggestion
1. Copy the SSH public key to your clipboard.
```

2022-02-24 23:55 UTC, ethanpalm commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
> +2. Copy the SSH public key to your clipboard.
```suggestion
1. Copy the SSH public key to your clipboard.
```

2022-02-24 23:55 UTC, ethanpalm commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
> +2. Copy the SSH public key to your clipboard.
```suggestion
1. Copy the SSH public key to your clipboard.
```

2022-02-24 23:55 UTC, ethanpalm commented on content/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.md
```suggestion

## Adding an SSH key to your account on {% data variables.product.product_name %}
```

This adds a new header to show where the procedure starts.

2022-03-18 17:45 UTC, closed without merging