Ghes workflow auth 15735
github/docs pull request #16301
Opened 2022-03-15 23:40 UTC by cmwilson21

### Why:

Closes [15735](https://github.com/github/docs/issues/15735)

### What's being changed:
Renamed section to "Authenticating an account on GitHub Enterprise Server" using variables.
Updated step 4 and added what happens after you click "continue" on step 4.
Added screen shot of Enterprise sign in form.
Removed reference to two factor auth. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2022-03-31 18:19 UTC, steveward requested changes
Thanks so much for working on this @cmwilson21! I've gone through and added comments about screenshots and wording that needs to be updated since we've made a bunch of minor changes in the app. 😬  Apologies for throwing additional things on, but it'd be great to get all this updated. If you have any questions let me know!

2022-04-01 12:17 UTC, steveward commented on content/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github.md
> +4. To add an account on {% data variables.product.product_location_enterprise %}, type the URL for your instance under "Enterprise server address," then click **Continue**.
```suggestion
4. To add an account on {% data variables.product.product_location_enterprise %}, type the URL for your instance under "Enterprise address," then click **Continue**.
```

2022-04-01 13:37 UTC, cmwilson21 commented on content/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github.md
>    {% data reusables.user-settings.password-authentication-deprecation-desktop %}
Got it! Will remove this reusable and the others mentioned in the review and will update per suggestions. Thanks!

2022-04-06 20:00 UTC, cmwilson21 commented
@steveward Thanks again for leaving the suggestions and feedback! The screenshots have been updated now, except for the Windows ones. I'm on Mac but I have a Windows machine here I will use and download Desktop on to grab those screenshots. Those bits will be updated soon! I'll reach out when they are done.

2022-04-13 17:29 UTC, cmwilson21 commented
Hey @steveward :) I updated the two windows images to reflect the recent changes. They looked fine on my screen, but when I see the preview in my codespace, they look a bit blurry. Can you check them out? Let me know if anything else needs to be done on them. Thanks!

2022-04-15 13:36 UTC, steveward approved these changes
Changes look great to me, thanks @cmwilson21!

2022-04-15 14:08 UTC, merged