Clarify how the bash shell will be invoked if not specified explicitlly
github/docs pull request #19192
Opened 2022-07-21 08:23 UTC by nikola-jokic

### Why:
This change is related to the https://github.com/actions/runner/issues/1955#issuecomment-1189337732 in the runner repo.
Closes #19191 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added one sentence stating that, if not specified explicitly, bash will be invoked with `bash -e {0}`

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2022-08-09 09:25 UTC, mattpollard requested changes
@nikola-jokic 👋🏻 If you could incorporate any changes from @eric-wieser and my comment, we'd greatly appreciate it 🙏🏻 Let us know when this is ready for a second look and we'll work with you to get it published.

2022-08-09 09:25 UTC, mattpollard commented on content/actions/using-workflows/workflow-syntax-for-github-actions.md
> +| All | `bash` | The default shell on non-Windows platforms with a fallback to `sh`. Bash will be invoked with `bash -e {0}` if the shell parameter is not specified explicitly. When specifying a bash
@eric-wieser's suggestion looks good 👍🏻 Should we still include @nikola-jokic's motion of `bash -e {0}`?

One thing I'd consider tweaking is this:

> Note that the behavior is different to specifying `bash` explicitly.

What's "the behavior" here? Can we be more explicit? "The behavior when not specifying `bash` in the path", etc.

2022-08-09 09:38 UTC, eric-wieser commented on content/actions/using-workflows/workflow-syntax-for-github-actions.md
> +| All | `bash` | The default shell on non-Windows platforms with a fallback to `sh`. Bash will be invoked with `bash -e {0}` if the shell parameter is not specified explicitly. When specifying a bash
"the behavior" is "the behavior described by this row of the table", which seems already clear to me.

2022-08-09 09:40 UTC, eric-wieser commented on content/actions/using-workflows/workflow-syntax-for-github-actions.md
> +| All | `bash` | The default shell on non-Windows platforms with a fallback to `sh`. Bash will be invoked with `bash -e {0}` if the shell parameter is not specified explicitly. When specifying a bash
Perhaps reordering the sentences would make it clearer?
```suggestion
| Linux / macOS | unspecified | The default shell on non-Windows platforms. Note that runs a different command to when `bash` is specified explicitly. If `bash` is not found in the path, this is treated as `sh`. | `bash -e {0}` |
| All | `bash` | The default shell on non-Windows platforms with a fallback to `sh`. When specifying a bash shell on Windows, the bash shell included with Git for Windows is used. | `bash --noprofile --norc -eo pipefail {0}` |
```

2022-08-09 14:33 UTC, nikola-jokic commented on content/actions/using-workflows/workflow-syntax-for-github-actions.md
> +| All | `bash` | The default shell on non-Windows platforms with a fallback to `sh`. Bash will be invoked with `bash -e {0}` if the shell parameter is not specified explicitly. When specifying a bash
@eric-wieser great suggestion! Thank you!

2022-08-09 14:47 UTC, nikola-jokic commented
Thank you so much @mattpollard for the review and @eric-wieser for suggestions! I applied the latest suggestion, and it seems clear to me. Since the flags are changing the way the action behaves (`--pipefail` for example is fail-fast behaviour), I would leave it as is. Not sure how to be more explicit there but if you want to change anything, I am happy to apply your changes, or you can commit it right away :relaxed:

2022-08-10 08:28 UTC, mattpollard approved these changes
Thanks for being open to feedback, @nikola-jokic! I'll merge this.

2022-08-10 08:49 UTC, merged

2022-08-10 08:54 UTC, tarek29577 commented
Stop ✋

في الأربعاء، ١٠ أغسطس ٢٠٢٢ ١٢:٥١ م github-actions[bot] <
***@***.***> كتب:

> Thanks very much for contributing! Your pull request has been merged 🎉
> You should see your changes appear on the site in approximately 24 hours.
> If you're looking for your next contribution, check out our help wanted
> issues
> <https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22>
> ⚡
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/docs/pull/19192#issuecomment-1210361898>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATGFBMFTWD35YMBMEUZPP6DVYNUP7ANCNFSM54GW2RDQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>