Update workflow-syntax-for-github-actions.md
github/docs pull request #19468
Opened 2022-08-01 10:26 UTC by isaranto

### Why:

Closes [issue link]

### What's being changed (if available, include any code snippets, screenshots, or gifs):
According to the [blogspot](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/)  there are other types of manual inputs that don't exist in the documentation. (`options` and `environment`)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2022-08-01 15:07 UTC, cmwilson21 commented
@isaranto Thanks so much for opening a PR! I'll get this triaged for review :zap:

2023-02-02 01:41 UTC, ajaykn requested changes
Thanks for trying to improve the docs.

We don't support `environment` or `choice` in workflow_call inputs.

So i see this PR changes are not correct.

2023-02-02 01:41 UTC, ajaykn commented on content/actions/using-workflows/workflow-syntax-for-github-actions.md
> +Required if input is defined for the `on.workflow_call` keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: `boolean`, `number`, `string`, `en
@isaranto this is related to workflow_call to pass inputs for reusable workflows
The blog [post](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/) you linked is related to workflow_dispatch which is for manually triggering inputs.

2023-02-03 16:11 UTC, cmwilson21 commented
@isaranto Thank you for opening a PR and for your patience as we are working through our backlog. Per the review above, we will not be accepting this contribution 💛 

We do hope you'll consider contributing again. Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 👍 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

2023-02-03 16:11 UTC, closed without merging