Clarifying stale UUID behavior
github/docs pull request #20514
Opened 2022-09-09 17:07 UTC by ronnie

Clarifying stale UUID behavior with new disks

### Why:

Closes request in [ZD#1731]](https://github.zendesk.com/agent/tickets/1731439) for documentation of stale UUID behavior.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2022-09-09 17:23 UTC, phongphansonthui commented
ในวันที่ ส. 10 ก.ย. 2022 00:16 น. github-actions[bot] <
***@***.***> เขียนว่า:

> Automatically generated comment ℹ️
>
> *This comment is automatically generated and will be overwritten every
> time changes are committed to this branch.*
>
> The table contains an overview of files in the content directory that
> have been changed in this pull request. It's provided to make it easy to
> review your changes on the staging site. Please note that changes to the
> data directory will not show up in this table.
> ------------------------------
> Content directory changes
>
> *You may find it useful to copy this table into the pull request summary.
> There you can edit it to share links to important articles or changes and
> to give a high-level overview of how the changes in your pull request
> support the overall goals of the pull request.*
> *Source* *Preview* *Production* *What Changed*
>
> admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance.md
> <https://github.com/github/docs/blob/73ed611ff7c4d75518228d02bb4a2bf5f6b22a56/content%2Fadmin%2Fconfiguration%2Fconfiguring-your-enterprise%2Fconfiguring-backups-on-your-appliance.md>
> ghes@ 3.6
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.5
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.4
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.3
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.2
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> ghes@ 3.6
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.5
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.4
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.3
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> 3.2
> ***@***.***/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance>
> ------------------------------
>
> fpt: Free, Pro, Team
> ghec: GitHub Enterprise Cloud
> ghes: GitHub Enterprise Server
> ghae: GitHub AE
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/docs/pull/20514#issuecomment-1242240313>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2KET5HLIJVLLAGSDWVZGJTV5NWFTANCNFSM6AAAAAAQI3IUWU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-09-09 21:54 UTC, ronnie commented
Previous looks okay to me.

2022-09-12 13:55 UTC, cmwilson21 commented
👋 @ronnie Thanks for opening a PR! I'll get it triaged for review ⚡

2022-10-04 23:58 UTC, vgrl requested changes
Thanks, @ronnie  ⚡ I'm going to make some changes to the language as discussed offline.

2022-10-05 00:11 UTC, vgrl approved these changes
The updated language looks good to me in [preview](https://docs-20514-5c1412.preview.ghdocs.com/en/enterprise-server@3.6/admin/configuration/configuring-your-enterprise/configuring-backups-on-your-appliance#restoring-a-backup).

@ronnie, please double check on preview and then I'll merge once you confirm all looks good! ⚡

2022-10-05 07:19 UTC, ayebabie384 reviewed
Need help

2022-10-12 21:45 UTC, briceholland commented
LGTM- Thanks @vgrl!

2022-10-12 21:45 UTC, ronnie commented
Looks good!

2022-10-12 21:53 UTC, merged