Fix indentation
github/docs pull request #22101
Opened 2022-11-17 20:10 UTC by rajbos

### Why:
Fix indentation in a list:
![image](https://user-images.githubusercontent.com/6085745/202549112-92a1eee7-5e74-4090-9397-5c6a524ca541.png)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2022-11-18 19:28 UTC, cmwilson21 commented
@rajbos Thanks so much for opening a PR! I'll get this triaged for review :zap:

2022-11-19 00:39 UTC, skedwards88 requested changes
Thanks for opening this PR! This indentation is intentional in order to show the breakdown of the 5000 minutes. Maybe a `:` after the first item can help clarify that? I added suggestions to demonstrate what I mean.

2022-11-19 00:39 UTC, skedwards88 commented on content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md
>  - 5,000 (3,000 Linux and 2,000 Windows) minutes = $56 USD ($24 USD + $32 USD).
```suggestion
- 5,000 (3,000 Linux and 2,000 Windows) minutes = $56 USD ($24 USD + $32 USD):
```

2022-11-19 00:39 UTC, skedwards88 commented on content/billing/managing-billing-for-github-actions/about-billing-for-github-actions.md
> +- 2,000 Windows minutes at $0.016 USD per minute = $32 USD.
```suggestion
  - 3,000 Linux minutes at $0.008 USD per minute = $24 USD.
  - 2,000 Windows minutes at $0.016 USD per minute = $32 USD.
```

2022-11-21 18:28 UTC, rajbos commented
I completely missed that. Still very subtle. Is it an idea to remove the first bullet on the 5000 minute line, end with a colon and then do a normal bulletted list? I think that would make it a lot more clear.

2023-04-05 09:36 UTC, closed without merging