Contributing: Fix links
github/docs pull request #249
Opened 2020-10-08 08:17 UTC by Simran-B

### Why:

Some of the links in CONTRIBUTING.md are broken.

### What's being changed:

Fix two typos and change anchor link to forking section, which does not have dedicated headlines for GitHub Desktop and command-line.

There are a couple more dead anchor links, but it looks like the content does not exist yet?

```md
- [Resolving merge conflicts](#resolving-merge-conflicts)
  - [In the GitHub user interface](#in-the-github-user-interface)
    - [Editing the file and committing the changes](#editing-the-file-and-committing-the-changes)
- [Troubleshooting](#troubleshooting)
  - [Failed status checks](#failed-status-checks)
- [Draft pull requests](#draft-pull-requests)
```

### Check off the following:

- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-08 19:22 UTC, janiceilene requested changes
Thanks for catching these @Simran-B! I added one suggestion. Once you accept that suggestion, we can review it again and get this merged in ⚡

2020-10-08 19:22 UTC, janiceilene commented on CONTRIBUTING.md
> +  - [Fork using GitHub Desktop or the command line](#ready-to-make-a-change-fork-the-repo)
```suggestion
```
We moved this information up to the top as well, so we can delete this line.

2020-10-08 20:44 UTC, Simran-B commented
You're welcome @janiceilene. Applied your suggestion. Can be merged, but you may want to address the remaining dead anchor links in another PR one way or the other.

2020-10-09 00:28 UTC, janiceilene commented
@Simran-B Thanks for pointing those out! We did some last minute restructuring of this doc and must have missed the table of contents 😅 Would you open an issue about the broken links you found? Maybe someone else will get to fixing them before I do 🤞 

I'll merge this in as soon as the branch is updated and all of the tests are green 💚

2020-10-09 00:31 UTC, janiceilene approved these changes

2020-10-09 01:27 UTC, merged

2020-10-09 01:27 UTC, janiceilene commented
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

2020-10-09 15:02 UTC, Simran-B commented
@all-contributors please add Simran-B for doc

2020-10-09 15:07 UTC, Simran-B commented
Sorry, wrong user 😞 

@all-contributors please add @Simran-B for doc