tweak grammar and punctuation for clarity
github/docs pull request #25630
Opened 2023-05-18 23:01 UTC by TallTed

### Why:

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2023-05-19 18:16 UTC, cmwilson21 commented
@TallTed Thanks so much for opening a PR! I'll get this triaged for review :zap:

2023-05-19 19:02 UTC, sabrowning1 requested changes
@TallTed thanks so much for finding these grammatical errors and opening a PR! ✨  I've made a few changes below; please let me know when you've committed them and I'll get this merged.

2023-05-24 12:08 UTC, sabrowning1 approved these changes
👋🏼 @TallTed, thanks again for your help with these grammatical errors! I've applied my suggestions and will go ahead and merge this to get these errors fixed 🙂 if you have any questions on my changes, feel free to take a look at the notes I left in my comments.

Thank you for your help maintaining our docs! ✨

2023-05-24 12:14 UTC, merged

2023-06-05 19:22 UTC, TallTed commented on contributing/translations-for-writers.md
> +| Avoid vague nouns and pronouns. | "Maintainers and contributors have access to files and comments. In the pull request they make changes to it." In this example it is not clear if the changes are b
Upon re-reading, I'd change `In this sentence, it is not clear what was deleted (a file or a folder).` to `In this sentence, it is not clear whether the user deleted the file or the folder.` Do you want another PR, or will you make this change directly?

2023-06-05 19:25 UTC, TallTed commented on contributing/translations-for-writers.md
> +| Avoid excessive use of stacked modifiers (noun strings). This can lead to incorrect translations, because it is not easy to tell what modifies what. | “public repository default source settings” or
I won't argue your changes. However, on rereading, I do suggest changing `"restrictions for OAuth app access."` to `"restrictions for app access via OAuth."` As earlier, do you want another PR, or would you change this directly?

2023-06-05 19:33 UTC, TallTed commented
Your comments and merge came through while I was on holiday. Let me know whether you want a new PR for my comments above, or you prefer to apply them directly.