Added a link to docs.github.com
github/docs pull request #260
Opened 2020-10-08 10:44 UTC by wi5nia

### Why:
Better UX

### What's being changed:
Added a links to docs.github.com

### Check off the following:
- [X] All of the tests are passing.
- [X] I have reviewed my changes in staging.
- [X] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [X] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-08 13:28 UTC, Simran-B requested changes

2020-10-08 13:28 UTC, Simran-B commented on README.md
> +This repository contains the documentation website code and Markdown source files for [docs.github.com](docs.github.com).
Should use a proper URL:
```suggestion
This repository contains the documentation website code and Markdown source files for [docs.github.com](https://docs.github.com).
```

Alternatively also `<https://docs.github.com>`, which renders as: <https://docs.github.com>

2020-10-08 20:52 UTC, janiceilene commented
Thanks @wi5nia 👍 I'll update this branch and merge when the tests are green 💚

2020-10-08 23:25 UTC, janiceilene approved these changes

2020-10-08 23:27 UTC, merged

2020-10-08 23:28 UTC, janiceilene commented
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

2020-10-09 07:18 UTC, wi5nia commented
@all-contributors please add wi5nia for doc