Make it clearer the Mars 2020 event has ended
github/docs pull request #26567
Opened 2023-07-10 16:30 UTC by minimalsm

### Why:

The current language wasn't clear that the event had ended and these badges are no longer attainable by new commits. You could argue that the date makes it clear, but I think it's better to be explicit.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.
  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2023-07-11 13:19 UTC, cmwilson21 commented
@minimalsm Thanks so much for opening a PR! I'll get this triaged for review :zap:

And welcome to the community! 🎉 

In the meantime, if you'd like to find other ways to contribute, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 👍

2023-08-07 13:22 UTC, supergranular requested changes
Hiya. Thanks for opening a PR and contributing to our docs. We agree it wasn't clear as well, and we think we can remove even more of the details since this is over.

2023-08-07 13:22 UTC, supergranular commented on content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
> +If you have authored any commit(s) present in the commit history for the listed tag of one or more of the repositories below, you'll receive the Mars 2020 Helicopter Contributor achievement on your p
```suggestion
The Mars 2020 Helicopter Contributor achievement was given to those who had authored a commit for one of the repositories listed below. This event has now ended, and the badge is no longer available. We built the list based on information received from NASA's Jet Propulsion Laboratory.
```

We think it wasn't clear as well, and we thought we could make it even shorter and clearer.

2023-09-18 12:35 UTC, supergranular approved these changes, later dismissed

2023-09-18 12:52 UTC, supergranular approved these changes

2023-09-18 12:56 UTC, merged