Update associating-an-email-with-your-gpg-key.md
github/docs pull request #2723
Opened 2021-01-09 16:43 UTC by layaxx

add necessary step to "associating an email with your gpg key"

### Why:
This is currently worded ambiguous and misses an important step.
See Issue #2722 

### What's being changed:
- improve wording to clarify that changes are confirmed but not saved at this point
- add a step to actually save the changes to the pgp key

### Check off the following:
- [] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-01-09 18:09 UTC, jace4411 approved these changes

2021-01-09 18:09 UTC, jace4411 approved these changes

2021-01-09 18:11 UTC, jace4411 approved these changes

2021-01-09 18:11 UTC, jace4411 approved these changes

2021-01-09 18:12 UTC, jace4411 approved these changes

2021-01-09 18:13 UTC, jace4411 approved these changes

2021-01-19 21:19 UTC, janiceilene commented
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

2021-01-21 09:35 UTC, Mesho098 requested changes

2021-01-21 09:35 UTC, Mesho098 commented on content/github/authenticating-to-github/associating-an-email-with-your-gpg-key.md
> +10. Enter `gpg --armor --export GPG key ID`, substituting in the GPG key ID you'd like to use. In the following example, the GPG key ID is `3AA5C34371567BD2`:
10. Enter `gpg --armor --export GPG key ID`, substituting in the GPG key ID you'd like to use. In the following example, the GPG key ID is `3AA5C34371567BD2`:

2021-02-02 09:47 UTC, felicitymay approved these changes
Hi @layaxx 👋🏻 

Thank you for raising this PR to fix the omission that you spotted. I checked your instructions and they work perfectly. Your changes look great and I'll update your branch and merge it now. 🎉

2021-02-02 09:57 UTC, merged

2021-06-20 01:39 UTC, mqdmm reviewed
سلام دوستان عزیز

2021-06-20 01:41 UTC, mqdmm reviewed
سلام دوستان عزیز @

2021-06-20 01:43 UTC, mqdmm reviewed
دوباره سلام به روی ماه نشسته شما.خیلی دوستتان دارم ❤️🤗❤️🧚🧚