feat: updates context menu shortcut for code nav
github/docs pull request #27307
Opened 2023-08-08 19:01 UTC by andrialexandrou

### Why:

Closes: 

No tracking issue, that I'm aware of

### What's being changed (if available, include any code snippets, screenshots, or gifs):

We needed to change the keyboard shortcut in Code Nav. Relevant conversation is in https://github.com/github/accessibility-audits/issues/4102. Now the docs need to be updated. 

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2023-08-09 19:58 UTC, cmwilson21 commented
👋 @andrialexandrou - Thanks so much for submitting a PR! I'll get this triaged for review :zap:

2023-08-11 12:00 UTC, hubwriter commented on content/get-started/using-github/keyboard-shortcuts.md
> +|<kbd>Option</kbd> (Mac)/<kbd>Alt</kbd> (Windows) + <kbd>Shift</kbd>+<kbd>C</kbd> | If a line of code is currently selected, this shortcut opens the line menu for that line, appearing under {% octico
This isn't expressed in the way we normally do things. Better to keep the whole key combo together:

```suggestion
|<kbd>Shift</kbd>+<kbd>Option</kbd>+<kbd>C</kbd> (Mac) or </br> <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>C</kbd> (Windows/Linux) | If a line of code is currently selected, this shortcut opens the line menu for that line, appearing under {% octicon "kebab-horizontal" aria-label="The horizontal kebab icon" %} to the left of the line
```

2023-08-11 12:02 UTC, hubwriter requested changes
@andrialexandrou - Thanks for raising this PR. 🎉 

One little suggested change. If this look ok please commit the suggestion and we'll get this merged.

Thanks again 👍

2023-08-14 22:55 UTC, andrialexandrou commented
Reviewed: https://docs-27307-a742a2.preview.ghdocs.com/en/get-started/using-github/keyboard-shortcuts#navigating-within-code-files

2023-08-15 08:28 UTC, hubwriter approved these changes

2023-08-15 08:34 UTC, merged