Update development.md
github/docs pull request #29000
Opened 2023-10-09 05:25 UTC by Harshdev098

### Why:

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs): 
 the readme link is not working in development.md file

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2023-10-10 03:09 UTC, Justin09111974 commented on contributing/development.md
branch

2023-10-10 03:27 UTC, Justin09111974 commented on contributing/development.md
branch

2023-10-10 03:33 UTC, Harshdev098 commented on contributing/development.md
Main

2023-10-13 20:53 UTC, steveward requested changes
Thanks for finding this broken link @Harshdev098! I found the correct link to the README that describes liquid tags, so I've added a suggestion with the correct link.

2023-10-13 20:53 UTC, steveward commented on contributing/development.md
> +- [tests/fixtures/README.md](tests/fixtures/README.md)
```suggestion
- [src/content-render/README.md](src/content-render/README.md)
```

2023-10-13 20:53 UTC, steveward commented on contributing/development.md
> +- [tests/fixtures/README.md](tests/fixtures/README.md)
This should be the correct link to the `content-render` section that discusses liquid tags.

2023-10-13 20:53 UTC, steveward commented on contributing/development.md
> +- Content is written in Markdown files, which are live in the `content` directory.
```suggestion
- Content is written in Markdown files, which live in the `content` directory.
```
The current wording here is correct, so I'm going to remove the "are" from this line.

2023-10-16 12:31 UTC, steveward approved these changes
Thanks!

2023-10-16 13:54 UTC, merged