docs: update information about package management
github/docs pull request #29086
Opened 2023-10-11 20:08 UTC by Rizina

### Why:

Closes: #27853

### What's being changed (if available, include any code snippets, screenshots, or gifs):

--

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2023-10-13 14:48 UTC, steveward requested changes, later dismissed
Thanks for the PR @Rizina! I'll get this triaged for review. ⚡

2023-10-13 14:48 UTC, steveward commented on content/rest/packages/packages.md
> +Github packages suppports a range of package manager for publishing packages. For more information, see "[AUTOTITLE](/packages/learn-github-packages/introduction-to-github-packages#supported-clients-
```suggestion
{% data variables.product.prodname_registry %} suppports a range of package managers for publishing packages. For more information, see "[AUTOTITLE](/packages/learn-github-packages/introduction-to-github-packages#supported-clients-and-formats)."
```

2023-10-13 16:00 UTC, sabrowning1 requested changes
👋🏼 @Rizina, thanks for opening another PR! ✨ I gave one small piece of feedback below; let me know if you have any questions 🙂

2023-10-16 15:20 UTC, sabrowning1 commented on content/rest/packages/packages.md
> +{% data variables.product.prodname_registry %} suppports a range of package managers for publishing packages. For more information, see "[AUTOTITLE](/packages/learn-github-packages/introduction-to-gi
```suggestion
{% data variables.product.prodname_registry %} supports a range of package managers for publishing packages. For more information, see "[AUTOTITLE](/packages/learn-github-packages/introduction-to-github-packages#supported-clients-and-formats)."
```

Tiny typo fix!

2023-10-16 15:22 UTC, sabrowning1 approved these changes
Thanks for making that change @Rizina! I fixed one small typo, and this now looks good to go 🚀 I'll merge it shortly.

We really appreciate your continued help improving our docs! If you are looking for other ways to contribute and are up for a challenge, check out our [pumpkin-spice label](https://github.com/github/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22pumpkin-spice%22+) to find help wanted issues that are a bit more in depth.

2023-10-16 15:32 UTC, merged