Add explicit k8s namespace for creating the ARC GitHub API PAT secret
github/docs pull request #29218
Opened 2023-10-17 23:53 UTC by adiroiban

### Why:

Closes: #29217

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Add explicit namespace in example.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2023-10-19 14:50 UTC, mchammer01 commented
The update looks good to me. Checking with the relevant team as I think that we may need to make a couple more similar updates. Will report back once I know more 😃

2023-10-19 17:11 UTC, adiroiban commented
Yes. This needs changes in other parts. I am not familiar with the build system for this site, so I just started this PR to start a conversation.

Maybe my suggestion is not correct.

But I think that is important to specificy in which namespace we need to create the secret.

My understanding, is that with the new ARC controller, the secret is only needed in the controller.

The runners will receive an already computed token needed to join the list of available runners.

2023-10-19 18:01 UTC, mchammer01 commented
@adiroiban - thanks for starting the conversation 😃 
Someone from the relevant focus team, who knows more than me on GitHub Actions, will review this as soon as they can.

2023-10-20 08:24 UTC, Link- commented on content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api.md
> +      --namespace=arc-systems \
```suggestion
      --namespace=arc-runners \
```

2023-10-20 08:30 UTC, Link- commented
Thank you @adiroiban for your contribution to making our docs better!

2023-10-20 08:32 UTC, Link- requested changes
Before we merge this, it'll be awesome to also add note here to clarify why we used the `arc-runners` namespace as opposed to `arc-systems`

![cs_2023-10-20_10-29-00](https://github.com/github/docs/assets/568794/b3b4103e-3bc5-4af7-9739-ab1c3991de42)

2023-10-20 17:35 UTC, jc-clark commented on content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api.md
>     ```bash copy
```suggestion
   {% note %}
   
   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For more information, see "[AUTOTITLE](/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller.md#configuring-a-runner-scale-set
).".
   
   {% endnote %}
   
   ```bash copy
```

2023-10-20 18:03 UTC, jc-clark commented on content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api.md
> +
```suggestion
1. To create a Kubernetes secret with the value of your {% data variables.product.pat_v1 %}, use the following command.
   {% note %}
   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For more information, see "[AUTOTITLE](/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller.md#configuring-a-runner-scale-set)."
   {% endnote %}
```

2023-10-20 18:13 UTC, jc-clark commented on content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api.md
> +   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For mo
```suggestion
   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For more information, see "[AUTOTITLE](/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#configuring-a-runner-scale-set)."
```

2023-10-20 18:45 UTC, jc-clark commented on content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api.md
> +
```suggestion
   {% note %}
   
   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For more information, see "[AUTOTITLE](/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#configuring-a-runner-scale-set)."

   {% endnote %}
   
```

2023-10-20 18:52 UTC, jc-clark commented on content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api.md
> +
```suggestion
   {% note %}

   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For more information, see "[AUTOTITLE](/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#configuring-a-runner-scale-set)."

   {% endnote %}

```

2023-10-20 19:03 UTC, jc-clark commented
@Link- Thank you for the review! Let us know what you think of the changes from the latest commits. If it looks good to you, I can help merge this content 👍

2023-10-20 21:34 UTC, adiroiban commented
Also, the "my_namespace" is refered in 2 places .

In the diff , it is only updated once.

Maybe that is ok.

![image](https://github.com/github/docs/assets/204609/fb1988fd-ac2a-4e88-a303-b30a53d6016e)


![image](https://github.com/github/docs/assets/204609/201afd2a-9ce7-46e6-8f2c-76ff17238c1c)

2023-10-20 22:51 UTC, adiroiban commented
I have tested it and is working ok.


Thanks for the fix :)

-------

I have previously reported an error, but it was something else.

It's a bit hard to troubleshoot errors that happen at pod `run` command level.
If a pod is scheduled by the controller but it fails to start, is not easy to track with with a barebone k8s cluster, as you can't retrie the logs post-mortem. 

ARC works. Thanks. Much appreciated

My issue was with the image `run` command. Now solved.

2023-10-21 11:49 UTC, Link- commented
Good point @adiroiban - @jc-clark I'm sorry to drag this a bit further, the current changes are 👍 can we please also introduce these changes?

### Change 1

![cs_2023-10-21_13-47-30](https://github.com/github/docs/assets/568794/b15b7796-0134-4918-a8b2-fdcfdc452043)

### Change 2

![cs_2023-10-21_13-47-48](https://github.com/github/docs/assets/568794/f625416f-07c1-4ea0-9169-d912310133db)

### Change 3

![cs_2023-10-21_13-48-11](https://github.com/github/docs/assets/568794/da2c1f6e-b65e-4444-98df-9533d87a9dfa)

2023-10-23 22:47 UTC, jc-clark commented
👋 Hello @adiroiban! I don't have permissions to commit changes to your pull request directly. Can you help us make the changes outlined by @Link- [above](https://github.com/github/docs/pull/29218#issuecomment-1773767052)? 

We will need to replace instances of `my_namespace` with `arc-runners` in those three locations. 

Let me know if you run into any issues adding this change to your pull request. And thank you in advance!

2023-10-24 14:27 UTC, adiroiban commented
Hi.

Sorry for the delay... this repo is huge :)

I got it on my computer and and I hope I got it right.

```
$ grep my_namespace  content/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/*
```

2023-10-24 20:13 UTC, jc-clark commented
No problem @adiroiban and apologies, I was not very clear in my last comment, so we missed part of @Link-'s suggestion. Sorry about that! 

I think we need to add the note about creating the secret in the right namespace to all three locations where we use this `arc-runners` example. 

To show the same information in multiple locations, we use [reusables](https://docs.github.com/en/contributing/writing-for-github-docs/creating-reusable-content). 

These are the steps to create a new reusable file and then reference it in multiple locations: 

1. Copy the following information into a new `.md` file in the [`data/reusables/actions` directory](https://github.com/github/docs/tree/main/data/reusables/actions directory). Save the file and name it `arc-runners-secret-namespace.md`. 

   ```
   {% note %}

   **Note:** Create the secret in the same namespace where the `gha-runner-scale-set` chart is installed. In this example, the namespace is `arc-runners` to match the quickstart documentation. For more information, see "[AUTOTITLE](/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#configuring-a-runner-scale-set)."

   {% endnote %}
   ```
1. Copy `{% data reusables.actions.arc-runners-secret-namespace %}` to your clipboard and paste it above the three locations where we use `arc-runners`
1. Commit your changes to this PR. 

Let me know if you run into any issues with this, I'll be happy to help out. And thank you for your patience while I missed this note before 😅

2023-10-25 18:09 UTC, jc-clark commented
Great catch @adiroiban! I think that name you suggested for the reusable would work perfectly.

2023-11-04 11:40 UTC, adiroiban commented
Sorry. I didn't had much time for this. Still spending the whole week getting ARC un and running on my homelab.

I have pushed a change. I hope it's good enough to merge.

2023-11-07 19:17 UTC, jc-clark commented
This looks amazing @adiroiban! Thanks for the changes. 🪩

We currently have a repo freeze happening, so I'll be able to merge this next week, when we are clear to publish docs again.

2023-11-07 19:17 UTC, jc-clark approved these changes

2023-11-14 15:43 UTC, merged