Clarify how to create a CNAME
github/docs pull request #2961
Opened 2021-01-18 01:15 UTC by ajs256

Clarify that users should create a CNAME in repo settings, rather than creating it directly. 

### Why:
Close issue #2184.

### What's being changed:
See the diff above

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-01-19 00:11 UTC, lucalves requested changes
Why remove code tags?

2021-01-19 00:18 UTC, ajs256 commented
Hmm. Don't know how that happened. It's fixed now!

2021-01-19 20:13 UTC, janiceilene commented
Thanks @ajs256! I'll get this triaged for review ✨

2021-01-19 20:14 UTC, lucalves approved these changes
Now, is ok to me!

2021-01-23 23:29 UTC, duc811997 reviewed
[Account 0.txt](https://github.com/github/docs/files/5861310/Account.0.txt)

2021-01-23 23:30 UTC, duc811997 approved these changes
[github-recovery-codes.txt](https://github.com/github/docs/files/5861312/github-recovery-codes.txt)

2021-01-23 23:37 UTC, ajs256 commented
Hey there @duc811997. I would strongly advise changing your recovery codes now, since you seem to have accidentally uploaded them. @janiceilene or someone else with permissions, could you please edit their comment to remove the file?

2021-01-27 17:38 UTC, ajs256 commented
Wait a minute, did I close this? I don't seem to be able to re-open it.

2021-01-28 19:48 UTC, janiceilene commented
Re-triaged!

2021-02-02 17:34 UTC, adonisj910 requested changes
git commit

Request changes

2021-02-02 17:34 UTC, adonisj910 commented on content/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site.md
>  ### Configuring a subdomain
https://GitHub.com/adonisj910.md

2021-02-02 17:39 UTC, adonisj910 reviewed
👍

2021-02-02 17:39 UTC, adonisj910 commented on content/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site.md
https://GitHub.com/adonisj910.md

2021-02-13 22:15 UTC, ajs256 commented
Looks like [your stalebot fix](https://github.com/github/docs/commit/f10360f689a3e8011ddc3050d636ee84fcdda096)isn't working...

2021-02-13 22:16 UTC, ajs256 commented
I can't re-open it, but I will not delete the branch so someone can re-open it and hopefully merge it.

2021-02-16 22:46 UTC, janiceilene commented
It looks like our new action inadvertently closed this :upside_down_face: Sorry about that! Reopening and triaging this for review :yellow_heart: Thanks for not deleting the branch!

2021-02-22 11:19 UTC, felicitymay approved these changes
Thanks for your PR and your patience with the technical glitches.

Your change looks good to me on our staging site: https://docs-2961--patch-2.herokuapp.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain. It clearly fixes the linked issue ✨

2021-02-22 16:08 UTC, merged