[Actions] Document authentication for service containers
github/docs pull request #29915
Opened 2023-11-13 04:24 UTC by ndench

Document how to authenticate with private registries and DockerHub when pulling images  for service containers.

### Why:

The documentation for service containers doesn't currently show how to specify credentials.
However, there's a [blog post from 2020 showing how to do it](https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/).

Closes: #29914

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The docs don't show how to specify credentials when using service containers. Credentials may be necessary to pull images from private registries or to authenticate with DockerHub in order to increase rate limits.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

2024-01-22 11:57 UTC, hubwriter requested changes
@ndench - Great change, many thanks for adding this! 👍 

Just one suggestion - which you can click to commit.

2024-01-22 11:57 UTC, hubwriter commented on content/actions/using-containerized-services/about-service-containers.md
> +Here’s an example of authenticating with DockerHub and GitHub Container Registry:
Use variables for the GH Container registry:

```suggestion
Here’s an example of authenticating with Docker Hub and the {% data variables.product.prodname_dotcom %} {% data variables.product.prodname_container_registry %}:
```

2024-02-05 10:38 UTC, hubwriter approved these changes

2024-02-05 10:38 UTC, hubwriter commented
Merging this now

2024-02-05 10:46 UTC, merged

2024-02-05 11:38 UTC, s3m13 commented
https://pin.it/7I9ZoqhgF