Update outdated CLI edit releases information
github/docs pull request #30241
Opened 2023-11-29 18:26 UTC by timsearle

### Why:

The website documentation is outdated - GitHub CLI does support editing releases.

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Following the convention in the "Create releases" section, show an example and a link to the GitHub CLI manual for the command.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2023-11-29 21:01 UTC, steveward commented
Thanks for the PR @timsearle! I'll get this triaged for review. ⚡

2023-12-19 15:49 UTC, sabrowning1 requested changes
👋🏼 @timsearle, thanks so much for catching this and raising a PR to update the docs! I've pushed a small formatting fix and left a few small comments below. Other than that, this is looking great! Once those suggestions have been applied, I'm happy to get this merged 🙂

2023-12-19 15:49 UTC, sabrowning1 commented on content/repositories/releasing-projects-on-github/managing-releases-in-a-repository.md
> +1. To edit a release, use the `gh release edit` subcommand. Replace `tag` with the tag representing the release you wish to edit. For example, to edit a given release's title:
```suggestion
1. To edit a release, use the `gh release edit` subcommand. Replace `TAG` with the tag representing the release you wish to edit. For example, to edit a given release's title, use the following code:
```

Just a couple small tweaks for ease of localization, and to adhere to our style guide.

2023-12-19 15:49 UTC, sabrowning1 commented on content/repositories/releasing-projects-on-github/managing-releases-in-a-repository.md
> +   gh release edit <tag> -t "New title"
```suggestion
   gh release edit TAG -t "New title"
```

One tiny change to align the formatting with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#placeholders).

2023-12-19 15:49 UTC, sabrowning1 commented on content/repositories/releasing-projects-on-github/managing-releases-in-a-repository.md
> +   For more information about possible arguments, see [the {% data variables.product.prodname_cli %} manual](https://cli.github.com/manual/gh_release_edit)
```suggestion
   For more information about possible arguments, see [the {% data variables.product.prodname_cli %} manual](https://cli.github.com/manual/gh_release_edit).
```

Small typo fix.

2023-12-19 19:40 UTC, timsearle commented
> 👋🏼 @timsearle, thanks so much for catching this and raising a PR to update the docs! I've pushed a small formatting fix and left a few small comments below. Other than that, this is looking great! Once those suggestions have been applied, I'm happy to get this merged 🙂

Thanks @sabrowning1 - especially for the commit suggestions, made it a lot quicker. Should all be done now.

2023-12-19 19:50 UTC, sabrowning1 reviewed
Apologies @timsearle, I missed updating one other placeholder 🤦🏼‍♂️ I'll go ahead and commit my suggestions, then get this merged. Thanks for your quick response, and for your help keeping our docs up-to-date! ✨

2023-12-19 19:50 UTC, sabrowning1 commented on content/repositories/releasing-projects-on-github/managing-releases-in-a-repository.md
> +   gh release edit TAG -t "New title"
```suggestion
   gh release edit TAG -t "NEW-TITLE"
```

2023-12-19 19:50 UTC, sabrowning1 commented on content/repositories/releasing-projects-on-github/managing-releases-in-a-repository.md
> +1. To edit a release, use the `gh release edit` subcommand. Replace `TAG` with the tag representing the release you wish to edit. For example, to edit a given release's title, use the following code:
```suggestion
1. To edit a release, use the `gh release edit` subcommand. Replace `TAG` with the tag representing the release you wish to edit. For example, to edit the title for a release, use the following code, replacing `NEW-TITLE` with the updated title:
```

2023-12-19 19:52 UTC, sabrowning1 approved these changes

2023-12-19 20:01 UTC, merged