Update upgrading-to-the-github-customer-agreement.md
github/docs pull request #30802
Opened 2023-12-23 17:14 UTC by carehart

Add links (in "Further Reading") to "Standard Terms" and "Customer Terms". 

### Why:
They are mentioned in the first paragraph of the text, while only the "Corporate Terms" (deprecated and seemingly not as important here) were linked to.

Someone may want to incorporate the links within the text as well/instead, but I realize that may not be desirable for some reason so did not propose that here.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Just adding two links.

### Check off the following:

- [x ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

(I could not find this "view deployment" feature "in this PR's timeline". I'm submitting this change via the github web UI. Since I'm following the pattern of a line already there, I'm going to ASSUME it would render ok. I confirmed my NEW links worked the same as the existing link whose pattern I used. )

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2023-12-23 17:27 UTC, carehart commented
Ah, ok. So only AFTER submitting the PR do we see the "view deployment" option. That's a bit confusing (to have to agree to having done it before it's possible.)

Anyway, I see now that there IS one problem--in that I had used the "autotitle" feature but it's not working for one of the two links I added. And I won't be able to edit this file whose commit I've offered (at least in the Github web UI for proposing doc changes, it doesn't seem possible.)

But lest someone close this due to that failure, I'll point out that the title for the page in question is, "Customer Terms", so if a maintainer seeing this wanted to slip in that change after/while accepting mine, that would resolve things.

Clearly, I'm not a pro-level github user--and I'm only using this web UI vs rebuilding the docs locally. I hope you can tell I'm simply trying to help improve the docs, as I am in fact reading them to better understand things. :-)

2023-12-25 03:27 UTC, Hoangkalo001 commented
Game

2023-12-26 18:09 UTC, nguyenalex836 commented
@carehart Thanks so much for opening a PR, and the thorough explanation on your thoughts process 💛 I'll get this triaged for review ✨

2024-01-02 07:42 UTC, subatoi requested changes
I've made a suggestion which should fix the broken link—I'll explain why in a separate comment

2024-01-02 07:42 UTC, subatoi commented on content/organizations/managing-organization-settings/upgrading-to-the-github-customer-agreement.md
> +- "[AUTOTITLE](https://github.com/customer-terms)."
```suggestion
- The [GitHub Customer Terms](https://github.com/customer-terms)
```

2024-01-02 07:47 UTC, subatoi commented
@carehart Thank you for raising a PR! I agree with the change you recommend here, in terms of customer experience.

A few things to note. I'll reply in-line to your comments:

> Ah, ok. So only AFTER submitting the PR do we see the "view deployment" option. That's a bit confusing (to have to agree to having done it before it's possible.)

Apologies this wasn't clear—you might find this page useful https://docs.github.com/en/contributing/collaborating-on-github-docs/about-contributing-to-github-docs#reviewing-your-own-pull-requests. I'll discuss internally whether there's anything more we can do to make that experience better for users. Another option would be to [run the documentation locally](https://docs.github.com/en/contributing/setting-up-your-environment-to-work-on-github-docs/creating-a-local-environment), so that you can see changes you make in a local preview instance, without needing to submit a PR first.

> Anyway, I see now that there IS one problem--in that I had used the "autotitle" feature but it's not working for one of the two links I added. 

You were quite right to use AUTOTITLE; the only problem was that that feature only works with `docs.github.com` pages, and the page in question is a `github.com` page. Hence my "suggestion" (see below comment for context).

> And I won't be able to edit this file whose commit I've offered (at least in the Github web UI for proposing doc changes, it doesn't seem possible.)

I've made a "[suggestion](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request)" that you can apply. I agree the Web UI is a little limited in this respect in terms of making further change. You should also have been able to make a "suggestion" yourself, even if that's a little bit awkward, so I've included the page in an in-line link at the start of this paragraph for your reference.

In any case, once we've resolved the outstanding point, I'll be happy to get this merged 😄

2024-01-11 17:14 UTC, subatoi approved these changes
We'll go ahead and merge this with the minor amendment—thank you for your submission!

2024-01-11 17:19 UTC, merged