Corrected documentation
github/docs pull request #31025
Opened 2024-01-10 01:42 UTC by C0derPr0

### Why:

Step 1 for the section "Configuring ReSharper for GitHub Copilot" and the associated image was incorrect.

Closes: [31013](https://github.com/github/docs/issues/31013)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I changed the incorrect content under the section "Configuring Resharper for GitHub Copilot."

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-01-10 16:03 UTC, nguyenalex836 commented
@C0derPr0 Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-01-19 12:17 UTC, hubwriter requested changes
@C0derPr0 - Many thanks for raising the docs issue, and this PR. 🎖️ 

I've made a couple of little suggestions which you can click to apply.

Thanks for including a screenshot but I don't think it's necessary here, and we've recently been trying to cut down on unnecessary screenshots in the docs. Could you delete the screenshot file from this PR? Thanks

2024-01-19 12:17 UTC, hubwriter commented on content/copilot/configuring-github-copilot/configuring-github-copilot-in-your-environment.md
> +1. In the Resharper menu bar, under **Extensions**, then **Resharper**, click **Options**.
It's the Visual Studio menu bar:
```suggestion
1. In the {% data variables.product.prodname_vs %} menu bar, under **Extensions**, click **ReSharper**, then click **Options**.
```

2024-01-19 12:17 UTC, hubwriter commented on content/copilot/configuring-github-copilot/configuring-github-copilot-in-your-environment.md
> +   ![Screenshot of Resharper menu bar. In the "Resharper" menu, the "Options" item is highlighted with an orange outline.](/assets/images/help/copilot/resharper-toolbar-options.png)
The screenshot doesn't match the style of our screenshots. However, I don't think we need a screenshot here. We should just delete this line.

```suggestion
```

2024-01-19 18:48 UTC, C0derPr0 commented
Sorry to be a bother..., but it says, "Merging is blocked until requested changes are addressed." I committed the requested changes, so I don't know why it is blocked.

2024-01-19 19:09 UTC, nguyenalex836 commented
@C0derPr0 Thanks for letting us know! @hubwriter may need to re-review after the suggestions have been committed, and I've just requested a re-review from him 💛

2024-01-22 09:05 UTC, hubwriter commented
Hi @C0derPr0 - thanks for making those changes.

Can you delete [resharper-toolbar-options.png](https://github.com/github/docs/pull/31025/files#diff-791530c19159e3de4546e02cf363fe585e304d7d1111cf5b6f6c7b50307a1339) from your branch? Then I'll get this merged.

2024-01-22 11:41 UTC, C0derPr0 commented
@hubwriter Okay, I deleted the image. Sorry about that, I committed your requested change several days ago and thought that included deleting the image.

2024-01-22 11:43 UTC, hubwriter approved these changes
@C0derPr0 - Great. Thanks for the quick response.

I'll get this merged now. Many thanks for helping with the docs. Much appreciated. 👍

2024-01-22 11:48 UTC, merged

2024-01-22 12:33 UTC, hubwriter commented
Now published:
https://docs.github.com/en/copilot/configuring-github-copilot/configuring-github-copilot-in-your-environment#configuring-resharper-for-github-copilot