Fix CodeQL default setup docs
github/docs pull request #31043
Opened 2024-01-10 20:18 UTC by FidelusAleksander

### Why:

If there are no supported languages found in the repository then the CodeQL setup is not available. The documentation seems  wrong.

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-01-10 21:06 UTC, nguyenalex836 commented
@FidelusAleksander Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-01-11 15:05 UTC, sabrowning1 requested changes
👋🏼 @FidelusAleksander, thanks for opening this PR! You're right, this content could use some clarification. I've requested some changes below; let me know when you've taken a look and I'll give this another review 🙂

2024-01-11 18:29 UTC, FidelusAleksander commented on content/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning.md
> +You can use default setup if your repository includes languages that are supported by {% data variables.product.prodname_codeql %}, such as Python or Java. For more information on {% data variables.p
LGTM @sabrowning1 !

2024-01-11 18:47 UTC, sabrowning1 approved these changes
This looks great @FidelusAleksander! I'll merge this shortly. Thanks again for your help maintaining our docs! 🚀

2024-01-11 18:51 UTC, merged