Update managing-repository-access-for-your-codespaces.md
github/docs pull request #31728
Opened 2024-02-20 02:48 UTC by adonm

### Why:

Makes clear wildcards can be used in the repositories variable.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-02-20 16:00 UTC, nguyenalex836 commented
@adonm Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-02-26 10:05 UTC, hubwriter requested changes

2024-02-26 19:47 UTC, nguyenalex836 commented on content/codespaces/managing-your-codespaces/managing-repository-access-for-your-codespaces.md
> +   **Note:** You can only reference repositories that belong to the same personal account or organization as the repository you are currently working in. To grant access to multiple repositories (e.g
@adonm I'll go ahead and commit this suggestion, then we'll merge this in! Thank you again for your contribution 💛

2024-02-26 19:48 UTC, nguyenalex836 approved these changes

2024-02-26 19:48 UTC, nguyenalex836 approved these changes

2024-02-26 19:49 UTC, nguyenalex836 submitted a review, later dismissed

2024-02-27 09:02 UTC, hubwriter commented on content/codespaces/managing-your-codespaces/managing-repository-access-for-your-codespaces.md
> +   - You can use the `*` wildcard to grant permissions to multiple repositories in an organization. For example, to grant permissions to all repositories in the `my_org` organization use `my_org/*`.
```suggestion
   - You can use the `*` wildcard to grant permissions to multiple repositories in an organization. For example, to grant permissions to all repositories in the `my_org` organization use `my_org/*`. This syntax is only valid for codespaces. In any `devcontainer.json` files that are used for prebuilds, you must define permissions for each repository separately. For more information, see "[AUTOTITLE](/codespaces/prebuilding-your-codespaces/allowing-a-prebuild-to-access-other-repositories)."
```

2024-02-27 09:02 UTC, hubwriter approved these changes

2024-02-27 09:14 UTC, merged