docs: Mismatch between explanation and code in triggers
github/docs pull request #33783
Opened 2024-07-01 20:21 UTC by gagan-bhullar-tech

### Why: To fix mismatch between explanation and code in triggers

Closes: #33777

### What's being changed (if available, include any code snippets, screenshots, or gifs):

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-07-01 21:09 UTC, nguyenalex836 commented
@gagan-bhullar-tech Hello! 👋 Thank you for opening a PR! 

We will need to put this PR on hold for now until the issue this PR is linked to has been reviewed by the team 💛

2024-07-02 10:28 UTC, hubwriter requested changes
@gagan-bhullar-tech - Many thanks for raising this PR with these changes.

As a result of feedback we've had, we are currently making an effort to reduce the number of links between articles, except where necessary to the understanding of the current article, so I've suggested removing the links here.

If you'd like to click to commit my suggestions then I'll approve this and we can get this merged next week once the current repo freeze is lifted.

Thanks again for working on this.
👍

2024-07-02 10:28 UTC, hubwriter commented on content/actions/publishing-packages/publishing-docker-images.md
> +Each time you create a new release on {% data variables.product.product_name %}, you can trigger a workflow to publish your image. The workflow in the example below runs when the `release` event trig
We could omit the link here:
```suggestion
Each time you create a new release on {% data variables.product.product_name %}, you can trigger a workflow to publish your image. The workflow in the example below runs when the `release` event triggers with the `published` activity type.
```

2024-07-02 10:28 UTC, hubwriter commented on content/actions/publishing-packages/publishing-docker-images.md
> +Each time you create a new release on {% data variables.product.product_name %}, you can trigger a workflow to publish your image. The workflow in the example below runs when the `release` event trig
Slight correction here, and again I think we can omit the link.

```suggestion
Each time you create a new release on {% data variables.product.product_name %}, you can trigger a workflow to publish your image. The workflow in the example below runs when a change is pushed to the `release` branch.
```

2024-07-02 18:18 UTC, gagan-bhullar-tech commented
@hubwriter thanks for reviewing. Incorporated both changes.

2024-07-03 08:40 UTC, hubwriter commented
@gagan-bhullar-tech - Many thanks. We'll merge this next week after the current repo freeze is lifted.
🚀

2024-07-03 08:40 UTC, hubwriter approved these changes

2024-07-08 00:02 UTC, merged