Update why-wasnt-my-application-for-a-student-developer-pack-approved.md
github/docs pull request #3415
Opened 2021-02-02 14:06 UTC by VibhuRajput

### Why:

### What's being changed:

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-02-02 16:53 UTC, janiceilene commented
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

2021-02-02 17:01 UTC, VibhuRajput commented
The initial doc was good but I made it more easy to understand for beginners and reduced the ambiguity by using descriptive language.

2021-02-04 12:52 UTC, HonkingGoose reviewed
What do you think of this wording?

2021-02-04 12:52 UTC, HonkingGoose commented on content/education/explore-the-benefits-of-teaching-and-learning-with-github-education/why-wasnt-my-application-for-a-student-developer-pack-approved.md
> +If the dates or schedule mentioned in your uploaded image doesn't matches our eligibility criteria, we require further proof of your academic status.
```suggestion
If the dates or schedule mentioned in your uploaded image do not match our eligibility criteria, we require further proof of your academic status.
```

2021-02-04 12:52 UTC, HonkingGoose commented on content/education/explore-the-benefits-of-teaching-and-learning-with-github-education/why-wasnt-my-application-for-a-student-developer-pack-approved.md
> +You're studying in a degree which is about to get terminated in current academic session (such as for 2021. If you're about to pass your degree by the mid of 2021.
```suggestion
You're pursuing a degree which will be terminated in the current academic session.
```

2021-02-04 19:42 UTC, janiceilene commented
@VibhuRajput Thanks so much for filling out the template! I've triaged this for the team ✨

2021-02-06 07:05 UTC, VibhuRajput commented
> @VibhuRajput Thanks so much for filling out the template! I've triaged this for the team ✨

Thanks @janiceilene

2021-02-19 11:25 UTC, MMLaws7 requested changes
I’m just asking for my changes

2021-02-19 11:26 UTC, MMLaws7 approved these changes

2021-02-25 15:45 UTC, myarb commented on content/education/explore-the-benefits-of-teaching-and-learning-with-github-education/why-wasnt-my-application-for-a-student-developer-pack-approved.md
> +You're pursuing a degree which will be terminated in the current academic session.
```suggestion
- You're pursuing a degree which will be terminated in the current academic session.
```

2021-02-25 15:48 UTC, myarb commented
Thanks so much for this PR, @VibhuRajput, and that great review, @HonkingGoose 🎉 I've committed your suggestions and we'll get this merged 🔜  ✨

2021-02-25 15:57 UTC, myarb approved these changes
Thanks so much for this PR, @VibhuRajput, and that great review, @HonkingGoose 🎉 I've committed your suggestions and we'll get this merged 🔜  ✨

2021-02-25 15:57 UTC, merged

2021-02-25 15:59 UTC, HonkingGoose commented
Cheers @myarb! Thanks for including my suggestions! 🎉

2021-04-03 23:02 UTC, R-BLIP885 commented
> ### Why:
> Made the document less ambiguous
> 
> ### What's being changed:
> The initial doc was good but I made it more easy to understand for beginners and reduced the ambiguity by using descriptive language.
> READY FOR REVIEW
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-04-04 02:45 UTC, SinEstresOrrantia approved these changes