Update GitHub desktop fork instructions
github/docs pull request #34151
Opened 2024-07-31 01:48 UTC by Nikkitory

### Why: The current fork instructions for Github desktop were out of date with the latest Github desktop.

Closes: https://github.com/desktop/desktop/issues/13165 (I realize this is an issue from a different repository, however in the comment thread of that issue you will see people mentioning that the issue arises because the docs here need updating.)

### What's being changed (if available, include any code snippets, screenshots, or gifs): Minor documentation changes, inluding updating screenshots. The easiest way to see the changes would be to look at the PRs file changes.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-07-31 21:17 UTC, nguyenalex836 commented
@Nikkitory Thank you so much for opening this PR! ✨ I have filed an internal issue to fix this on our end, as this portion of the documentation will need to be updated by our team 💛

Thanks again for raising a flag on this ✨

2024-08-05 15:18 UTC, nguyenalex836 commented
@Nikkitory Apologies for the confusion, but it looks like these changes may not need to be made internally 💛 I'm reopening this PR, and one of our team members will review shortly. Thank you!

2024-08-16 18:47 UTC, steveward requested changes
Thanks for submitting this pull request @nikkitory! I've left comments for some changes I'd like to see made. Mainly, I'd like to keep the original screenshots and reusables and instead add new ones that represent the updates you were making to the originals. If you have any questions or need additional clarity, please let me know!

2024-08-16 18:47 UTC, steveward commented on assets/images/help/desktop/clone-choose-button-mac.png
Let's keep the original screenshot and add this as a new screenshot.

2024-08-16 18:47 UTC, steveward commented on data/reusables/desktop/cloning-location-tab.md
Let's keep this reusable and create a new one with the URL tab option.

2024-08-16 18:47 UTC, steveward commented on data/reusables/desktop/cloning-repository-list.md
Same as above --  let's keep this reusable as is and create a new one specific to cloning via a URL.

2024-08-23 19:21 UTC, closed without merging

2025-01-22 00:11 UTC, warp-core commented
Would it be ok if I copied the head branch from here, made the requested changes, and created a new pull request?

2025-01-22 16:49 UTC, nguyenalex836 commented
@warp-core Please do! 💛