Bugfix creating-a-composite-action.md
github/docs pull request #34197
Opened 2024-08-05 07:03 UTC by misafu

Existing template incorrectly uses 'actions' where <username> should be present.

### Why:

Closes: 

https://github.com/github/docs/issues/34196

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The template is and instructions are changed to specify the user's username should be used, not the word 'actions'

### Check off the following:

- [ X] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ X] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-08-05 16:35 UTC, nguyenalex836 commented
@misafu Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-08-06 11:43 UTC, subatoi requested changes
Hi @misafu — I agree this is slightly misleading. I've made suggestions based on our [placeholder guidance](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#placeholders), and the fact that repository _owner_ would be more appropriate (and applicable in every circumstance).

2024-08-06 11:43 UTC, subatoi commented on content/actions/creating-actions/creating-a-composite-action.md
> +Copy the workflow code into a `.github/workflows/main.yml` file in another repository, but replace `<username>/hello-world-composite-action@v1` with your <username> and the repository and tag you cre
```suggestion
Copy the workflow code into a `.github/workflows/main.yml` file in another repository, replacing `OWNER` and `TAG` with the repository owner and the tag you created, respectively. You can also replace the `who-to-greet` input with your name.
```

2024-08-06 11:43 UTC, subatoi commented on content/actions/creating-actions/creating-a-composite-action.md
> +        uses: <username>/hello-world-composite-action@v1
```suggestion
        uses: OWNER/hello-world-composite-action@TAG
```

2024-08-07 07:20 UTC, subatoi approved these changes
Thank you! I'll go ahead and get this merged. 

Thanks for your interest in the GitHub Docs!

2024-08-07 07:25 UTC, merged