Update jetbrains-compatible-ides.md by adding Writeside
github/docs pull request #34626
Opened 2024-09-17 19:22 UTC by MrArnaudMichel

Adding Jetbrains Writeside on the jetbrains compatible IDE.

Writeside (https://www.jetbrains.com/fr-fr/writerside/) is an IDE to create documentation

### Why:

Closes: https://github.com/github/docs/issues/34625

JetBrains Writeside is an IDE for creating documentation, and this update ensures that it is reflected in the list of JetBrains IDEs compatible with GitHub Copilot. This will help users who work in documentation and are looking for Copilot support within their preferred JetBrains IDE.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Before:
```
......
* RubyMine
* RustRover
* WebStorm
```

After:
```
......
* RubyMine
* RustRover
* WebStorm
* Writeside
```

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-09-17 20:15 UTC, nguyenalex836 commented
@MrArnaudMichel Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-10-01 13:58 UTC, sabrowning1 requested changes
👋🏼 @MrArnaudMichel, thanks for raising a PR to close your issue! This change makes sense to me; I've just left one small comment below fixing a typo in the [IDE name](https://www.jetbrains.com/writerside/). After you've applied that suggestion, we'll get this merged once our repo freeze ends on October 7th 🙂

2024-10-01 14:55 UTC, nguyenalex836 commented
@MrArnaudMichel Thank you very much for the typo fix! ✨ This repo is currently in a code freeze, but we will get this merged as soon as the freeze ends on 10/7! 🍏

2024-10-01 15:08 UTC, sabrowning1 approved these changes
@MrArnaudMichel looks great, thanks again for your help keeping our docs up-to-date!

I misspoke earlier—as @nguyenalex836 said, we'll get this merged after the repo freeze ends on October 7th 😄

2024-10-07 15:44 UTC, merged