Update metadata-syntax-for-github-actions.md
github/docs pull request #3468
Opened 2021-02-04 13:32 UTC by mambax

I tried to use another name than Dockerfile, the build fails saying:

`docker: invalid reference format: repository name must be lowercase.`

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-02-04 19:10 UTC, kadirselcuk approved these changes

2021-02-04 19:54 UTC, janiceilene commented
@mambax Thanks so much for opening a PR! I'll get this triaged for review ✨

2021-02-05 02:32 UTC, Stevenans66 submitted a review, later dismissed

2021-02-16 20:40 UTC, janiceilene commented
@mambax It looks like our new action inadvertently closed this 😢 I'm so sorry about that! We're merging a fix right now.

2021-02-16 21:42 UTC, mambax commented
@janiceilene I thought its a bit weird. Should I restore my branch?

2021-02-16 21:42 UTC, mambax commented
/reopen

2021-02-17 02:55 UTC, janiceilene commented
Thank you so much for restoring your branch! I'll get this back up for review 💖

2021-03-03 16:57 UTC, hubwriter requested changes
@mambax - Many thanks for pushing this PR. It'll be good to clarify this point that isn't currently clear. We appreciate you helping us improve the docs! Thanks again. 👍

2021-03-03 16:57 UTC, hubwriter commented on content/actions/creating-actions/metadata-syntax-for-github-actions.md
> +**Required** The Docker image to use as the container to run the action. The value can be the Docker base image name, a local `Dockerfile` in your repository, or a public image in Docker Hub or anoth
I think the sentence might be simpler to parse without the parentheses. Maybe change this to:
```suggestion
**Required** The Docker image to use as the container to run the action. The value can be the Docker base image name, a local `Dockerfile` in your repository, or a public image in Docker Hub or another registry. To reference a `Dockerfile` local to your repository, the file must be named `Dockerfile` and you must use a path relative to your action metadata file. The `docker` application will execute this file.
```

2021-03-04 08:57 UTC, hubwriter approved these changes
@mambax - great, thanks again, I'll get this merged so that this change goes live. 🎉

2021-03-04 14:11 UTC, merged