sarif-support-for-code-scanning.md:`runAutomationDetails` fix
github/docs pull request #34820
Opened 2024-10-03 08:47 UTC by SwuduSusuwu

The previous example was "2021-02-01 == February 2, 2021" which is not normal calendar use. The new example fixes this.

### Why:

Closes: https://github.com/github/docs/issues/34819

### What's being changed (if available, include any code snippets, screenshots, or gifs):

### Check off the following:

- [ X ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ X ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-10-03 17:28 UTC, nguyenalex836 commented
@SwuduSusuwu Thank you for opening a PR! I believe this doc is following [ISO date format](https://www.w3.org/QA/Tips/iso-date#:~:text=The%20ISO%20date%20format,the%20day%20%5B01%20to%2031%5D), which should actually mean `2021-02-01 == February 1, 2021`!

I'll get this triaged for review, just so another member of the team can confirm 💛

2024-10-04 07:23 UTC, subatoi requested changes, later dismissed
Hi @SwuduSusuwu and thanks for raising a PR. You're right about the mistake.

Instead of just changing the written part to match the correct date, we should delete it altogether: different countries use different dates and not everyone follows ISO8601, sadly. Stating the date doesn't add anything, either.

Once we resolve that point we can merge this on October 7th, after our freeze ends. Thank you!

2024-10-04 07:23 UTC, subatoi commented on content/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning.md
> +* The run with an `id` of "my-analysis/tool1/2021-02-01" belongs to the category "my-analysis/tool1". Presumably, this is the run from January 2, 2022.
```suggestion
* The run with an `id` of "my-analysis/tool1/2021-02-01" belongs to the category "my-analysis/tool1".
```

2024-10-07 07:28 UTC, subatoi commented
Hi, I appreciate what you're trying to say with the new changes, but we'd be better off keeping this simple and simply delete the line I noted in my last suggestion.

2024-10-10 20:43 UTC, nguyenalex836 commented
@SwuduSusuwu Hello! 👋 Just wanted to make sure you saw @subatoi's last comment. Once you've deleted the note that he referenced, we'll be happy to get his merged 💛

2024-10-17 21:31 UTC, nguyenalex836 approved these changes

2024-10-17 21:32 UTC, nguyenalex836 commented
@SwuduSusuwu I went ahead and removed the line noted in @subatoi's suggestion 💛 We'll go ahead and get this merged - thank you for raising a flag on this issue, and contributing to GitHub Docs! ✨

2024-10-17 21:43 UTC, merged