Disabling two-factor authentication documentation update
github/docs pull request #34830
Opened 2024-10-04 00:46 UTC by georgethemarmot

### Why:
Documentation was not up to date with website changes

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Image and description of where to disable 2fa

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-10-04 14:28 UTC, nguyenalex836 commented
@georgethemarmot Thank you for opening a PR! ✨ While your changes appear to be correct, I'll get this triaged for review by our technical writing team to validate content / style changes 💛

2024-10-24 10:42 UTC, kashyapanjali commented
how can i contribute ?

2024-10-24 14:43 UTC, nguyenalex836 commented
@kashyapanjali Hello! 👋 While there aren't any opportunities to contribute regarding this PR, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨

2024-11-11 06:17 UTC, yyy7u commented on content/authentication/securing-your-account-with-two-factor-authentication-2fa/disabling-two-factor-authentication-for-your-personal-account.md
> +   ![Screenshot of an account's 2FA settings. The option menu is outlined in red.](/assets/images/help/2fa/disable-two-factor-authentication.png)
georgethemarmot:main

2024-11-18 08:46 UTC, subatoi requested changes
Hi @georgethemarmot—

Thanks for raising this PR and identifying the discrepancy. You're absolutely right that we need to change this, but I've amended your proposals to fit with our style guide.

One more thing is that the image you've proposed doesn't conform to the guidelines in https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots so I created a new one that I'll add in a comment below, that you can add to your branch.

Once you've accepted all the changes we can get this merged. Many thanks!

2024-11-18 08:46 UTC, subatoi commented
<img width="1021" alt="disable-two-factor-authentication" src="https://github.com/user-attachments/assets/870beada-89ab-46b9-872a-b6ba07003bd9">

New image to use

2024-11-26 18:39 UTC, nguyenalex836 commented
@georgethemarmot Howdy! 👋 We wanted to check in and see if you've had a chance to review @subatoi's suggestions, including the new image he provided! The branch conflicts will also need to be resolved as well 💛 

If you'd rather us fix this internally, we're more than happy to do so!

2024-12-03 19:23 UTC, closed without merging

2024-12-04 08:55 UTC, subatoi commented
@georgethemarmot Just to let you know, I'm shipping a fix for this internally and have added you as a co-committer (since you use a no-reply), so we can leave this closed.

Thanks for spotting this and your interest in the docs!

2024-12-08 16:55 UTC, georgethemarmot commented
@nguyenalex836  @subatoi  
Sorry I had no time to reply before. 
Next time I'll maybe just report it instead of opening PR.

2024-12-09 07:42 UTC, subatoi commented
> Sorry I had no time to reply before.

No problem at all!

> Next time I'll maybe just report it instead of opening PR.

In general, that's often the best way to do things. We don't mind people raising PRs first, but since we have to conform to our style guide and restrictions around images (like in this case), it can introduce a bit of friction. If users raise an issue first, it gives us chance to help shape the changes, meaning, typically, less friction. Obviously there isn't much point in raising an issue first if you're only fixing a typo, though!

In this case, I went ahead and pushed a fix because you'd correctly identified something that might have been tripping people up, so thank you again!

You can see your co-committer attribution here:

https://github.com/github/docs/commit/1368bab5336e46d95d15cacd43aeb955d1353e54