repo sync
github/docs pull request #3501
Opened 2021-02-05 19:36 UTC by Octomerger

This is an automated pull request to sync changes between the public and private repos.

:robot: This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!

2021-02-05 19:38 UTC, merged

2021-02-08 09:43 UTC, Bo886 commented
I

2021-02-08 09:44 UTC, Bo886 reviewed
n

2021-02-08 09:44 UTC, Bo886 commented on .github/workflows/update-graphql-files.yml
> -      - if: ${{ steps.create-pull-request.outputs.pr_number }}
I

2021-02-08 09:44 UTC, Bo886 commented on .github/workflows/update-graphql-files.yml
> +          number: ${{ steps.create-pull-request.outputs.pull-request-number }}
P

2021-05-13 10:47 UTC, gangster1313 requested changes
Attach