[education] add documentation for configuring Blackboard LMS
github/docs pull request #35028
Opened 2024-10-21 06:59 UTC by scollovati

### Why:

Closes: https://github.com/orgs/community/discussions/44066

### What's being changed (if available, include any code snippets, screenshots, or gifs):

This PR adds documentation for properly configuring the GitHub Classroom integration with Anthology Blackboard LMS. This LMS is fully compliant with [[LTI1.3 Advantage](https://site.imsglobal.org/certifications/anthology/blackboard-learn)](https://site.imsglobal.org/certifications/anthology/blackboard-learn), particularly the NRPS service used by GitHub Classroom for roster synchronization.

If this PR is accepted, we suggest the following improvements:

1.  Add “Blackboard” as an LMS option in the dropdown menu on the registration page (https://classroom.github.com/register-lms).
2.  Change “Other” to “Blackboard” in the relevant code section (step #3 in `register-a-learning-management-system-with-github-classroom.md`).

Important note: The optimal integration method for GitHub Classroom into Blackboard would involve GitHub managing a global registration in the Anthology Developer Portal (step #1 in `register-a-learning-management-system-with-github-classroom.md`). This approach is recommended by [[Anthology](https://docs.anthology.com/docs/blackboard/lti/1.3/best-practices#why-vendor-tool-registration-is-best)](https://docs.anthology.com/docs/blackboard/lti/1.3/best-practices#why-vendor-tool-registration-is-best), as it allows each institutional deployment to be distinguished by its `deploymentId` and platform URL. However, `deploymentId` is not currently a configurable field on https://classroom.github.com/register-lms. Therefore, the registration flow proposed in this PR, which creates a unique `clientId` for each institution, is currently the only feasible option.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-10-21 18:57 UTC, Zisafaruk commented
[Uploading guidingprinciplesbusinesshr_en.pdf…]()

2024-10-21 19:04 UTC, nguyenalex836 commented
@scollovati Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-10-30 16:52 UTC, scollovati commented
> @scollovati Thanks so much for opening a PR! I'll get this triaged for review ✨

@nguyenalex836 may I help in finding a SME to review this?

2024-10-30 17:40 UTC, nguyenalex836 commented
@scollovati That's very kind of you! Our internal SME team is actually reviewing this now. Once they have an update to provide, we will post here 💛

2024-12-13 09:28 UTC, scollovati commented
@nguyenalex836 may I help somehow? I see that also the bot has a bug, since it says "add a comment or push a commit within 3 days" but it immediately closes the PR.

2024-12-13 15:27 UTC, nguyenalex836 commented
@scollovati Apologies on behalf of our bot! I've reopened this PR. Our team is still in the process of reviewing, but you'll receive an update as soon as we have more info 💛

2025-01-08 10:41 UTC, scollovati commented
@nguyenalex836 May I ask why the PR has been closed? When an SME will provide a review?

2025-01-08 11:03 UTC, baki3344 commented
https://github.com/github/docs/pull/35028#issuecomment-2577353328

2025-01-08 19:41 UTC, nguyenalex836 commented
@scollovati Apologies on behalf of our bot! I've just reopened this issue 💛 While we still don't have an ETA from our SMEs on a review, we'll nudge them once more to take a peek when they are able. Thank you for your patience!

2025-02-03 08:15 UTC, scollovati commented
@nguyenalex836 Sorry that my PR is not meaningful for Github. Furthermore, there is a clear bug in the bot since it says "A stale label has been added to this pull request because it has been open 7 days with no activity. To keep this PR open, add a comment or push a commit within 3 days." but instead it closes it immediately.

2025-02-10 18:22 UTC, avni commented
@nguyenalex836 can you please assign this to @dhanachavan. She has recently joined GitHub Education and will test/take a look. Thank you!

2025-02-19 13:52 UTC, dhanachavan commented
Hi @nguyenalex836 @avni I will work through this by end of next week at the latest and update you on this thread.

2025-03-05 16:58 UTC, dhanachavan commented
Working on this issue and will have a final summary soon. Thank you for your patience !

2025-03-06 06:38 UTC, jaisunislam1111 commented
c52deadd4577d5ec356e2197b55bdd98daf696cc

2025-03-06 06:38 UTC, jaisunislam1111 commented
#36639

2025-03-29 14:52 UTC, dhanachavan commented
WIP

2025-03-29 15:52 UTC, Nonthawat100 commented
😁😁😁😁

2025-03-30 17:25 UTC, KnightOWL559 commented
Hello  sorry I'm having  trouble  WItH a sync app my PC TH

Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Mar 29, 2025 at 9:00 AM, นลธวัช ***@***.***> wrote:    
😁😁😁😁

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
Nonthawat100 left a comment (github/docs#35028)
😁😁😁😁

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2025-04-14 12:25 UTC, Milanhe92 commented
https://github.com/community/community/blob/a212693f55853b806b8d7c32d97a537c4994e7ee/CODE_OF_CONDUCT.mdpackage.jsonpackage-lock.jsonhttps://milanhe92.live/Milanhe92.live

2025-04-24 04:30 UTC, dhanachavan commented
**Update Apr 24, 2025**
- Created GitHub Test Accounts
- Created trial Blackboard account
- Registered Developer Keys in the Anthology Developer Portal

2025-04-29 14:40 UTC, scollovati commented
> I am trying to Register Developer Keys in Blackboard using the following steps with my trial Blackboard account. URL: [trial.blackboard.com](http://trial.blackboard.com/)
> 
> But I am unable to view the "Admin" tab or the "LTI Tool Providers" in step#2 . I have sent an email to [community@blackboard.com](mailto:community@blackboard.com) for help.
> 
>     1. Sign into your **Blackboard** instance.
> 
>     2. In the left sidebar on the home page, click **Admin**, then click **LTI Tool Providers**.
> 
>     3. On the "LTI Tool Providers" page, click **Register LTI 1.3/Advantage Tool**.
> 
>     4. Insert the **Client ID** obtained from the Developer Portal and click **Submit**.

You need to use a Licensed version of Blackboard in order to access the admin panel, for example here are instructions for setting up an AMI: https://docs.anthology.com/docs/developer-ami. Better if you write to [developers@anthology.com](mailto:developers@anthology.com) for getting help.

2025-04-29 14:48 UTC, dhanachavan commented
Thank you for the guidance, @scollovati ❤️

2025-04-30 20:35 UTC, OneComputerGuy commented
Hi @dhanachavan, Stefano contacted us regarding this request. My name is Sebastian and I'm part of the Partner Enablement team from Anthology.

Let me know if there's any help needed for an environment where the steps can be tested, I can help in that regard if needed.

2025-05-02 12:31 UTC, dhanachavan commented
Thanks a ton, @OneComputerGuy  and @scollovati  for your help ! ❤️ 
Yes, I would love to get the environment for testing this out. I have responded to your email as well.

2025-05-06 14:01 UTC, dhanachavan commented
Status Update May 6, 2025
--

Thanks to the test environment setup by @OneComputerGuy, I was able to follow the remaining instructions in file **register-a-learning-management-system-with-github-classroom.md**

1. Registered Developer Keys in Blackboard
**Note** - Instructions mentioned Insert the **Client ID** obtained from the Developer Portal and click **Submit**. There was no **Client ID** in the previous step, so I added the **Application ID** instead, and it worked fine.

2. Registered developer keys with GitHub Classroom
**Note** - Instructions mentioned * "Client ID": The "Client ID" obtained from the registration of the app in the Anthology Developer Portal. There was no **Client ID** in the previous step, so I added the **Application ID** instead, and it worked fine.

In order to proceed with instructions in file **connect-a-learning-management-system-course-to-a-classroom.md**, to link a Blackboard course with a classroom , I am awaiting confirmation on whether the trial Blackboard instance would work, or I need to spin up an AMI instance.

2025-05-14 14:53 UTC, dhanachavan requested changes
Hi, thanks for submitting this PR. I have added additional comments for options that don't show up and what the alternative option for a new Blackboard user would be.

2025-05-18 09:04 UTC, viviarentals commented
UTM codes will be added to your redirect URL after successful payments as shown below:

viviarentals.com/?utm_source=google&utm_campaign=rentals_may_2025&utm_medium=organic&utm_content=cta_banner&utm_term=rent_only_listings
--------------------------------------------------------------------------------------------------
https://billing.viviarentals.com/b/aEU6pJ9d9aRhgNOaEF?prefilled_email=viviarentals-wallet-service%40resounding-node-456217-h1.iam.gserviceaccount.com&client_reference_id=resounding-node-456217-h1&locale=en&utm_source=google&utm_campaign=rentals_may_2025&utm_medium=organic&utm_content=cta_banner&utm_term=rent_only_listings

2025-05-21 09:20 UTC, scollovati commented on content/education/manage-coursework-with-github-classroom/teach-with-github-classroom/connect-a-learning-management-system-course-to-a-classroom.md
> +1. In the rigth sidebar on the course page, click **Books & Tools**, then click **GitHub Classroom**. Note that the name may be different if your LMS admin named it something else when registering yo
Thanks, fixed here: https://github.com/github/docs/pull/35028/commits/26f5b2dc31cd6370ac2b3922659fbfa92a41a13a

2025-05-21 09:21 UTC, scollovati commented on content/education/manage-coursework-with-github-classroom/teach-with-github-classroom/connect-a-learning-management-system-course-to-a-classroom.md
> +1. Clicking the **GitHub Classroom** button will launch you into {% data variables.product.prodname_classroom %}, where you can select a classroom to link with your LMS course.
Thanks, fixed here: https://github.com/github/docs/pull/35028/commits/26f5b2dc31cd6370ac2b3922659fbfa92a41a13a

2025-05-21 09:21 UTC, scollovati commented on content/education/manage-coursework-with-github-classroom/teach-with-github-classroom/register-a-learning-management-system-with-github-classroom.md
> +   * "Client ID": The "Client ID" obtained from the registration of the app in the Anthology Developer Portal.
Thanks, fixed here: https://github.com/github/docs/pull/35028/commits/26f5b2dc31cd6370ac2b3922659fbfa92a41a13a

2025-05-21 09:21 UTC, scollovati commented on data/reusables/classroom/supported-lmses.md
> +* Blackboard
Thanks, fixed here: https://github.com/github/docs/pull/35028/commits/26f5b2dc31cd6370ac2b3922659fbfa92a41a13a

2025-05-21 09:21 UTC, scollovati commented on content/education/manage-coursework-with-github-classroom/teach-with-github-classroom/register-a-learning-management-system-with-github-classroom.md
> +    1. Verify that **Allow mark service access** radio button is set to "No".
Thanks, fixed here: https://github.com/github/docs/pull/35028/commits/26f5b2dc31cd6370ac2b3922659fbfa92a41a13a

2025-05-21 09:22 UTC, scollovati commented on content/education/manage-coursework-with-github-classroom/teach-with-github-classroom/connect-a-learning-management-system-course-to-a-classroom.md
> +1. Select the Blackboard course or organization to integrate with {% data variables.product.prodname_classroom %}.
See my comment here https://github.com/github/docs/pull/35028#discussion_r2099803860

2025-05-27 09:31 UTC, dhanachavan approved these changes
Approved, after the PR review changes were committed.

2025-05-27 23:31 UTC, jc-clark reviewed
Overall this looks really good from a docs content perspective @scollovati! Thanks for making these updates and thank you for reviewing @dhanachavan. 

I've suggested a few formatting changes below. Once you have a chance to work through these, I can take another look and then merge these docs in.

2025-05-28 06:55 UTC, scollovati commented
> I've suggested a few formatting changes below. Once you have a chance to work through these, I can take another look and then merge these docs in.
Thank you @jc-clark :) Done here: 020ba7bff7d1f7d2c39426e806ef898e1e34c385

2025-05-28 17:28 UTC, jc-clark approved these changes
Looks great to me! Thanks for this contribution @scollovati. And thank you for the review @dhanachavan! 

I'll go ahead and merge.

2025-05-28 17:39 UTC, merged

2025-05-28 18:02 UTC, Milanhe92 commented
Good job.