When informing of a regex syntax let's do it with required separators…
github/docs pull request #35234
Opened 2024-11-08 19:09 UTC by nbenitez

… in-place

If we inform the user about how to make a case sensitive search using a regex syntax, do it with the regex delimitators in place, so the user:

- Don't gets an error when copying and pasting the regex syntax to the github code search textbox. Error meaning it didn't find results because it lacks the regex slash separators.

- Avoid the user to have to also find in the documentation how to enter a regex in the code search textbox. Have to find out it needs to use the slash separators.

### Why:

Because a user checking docs of GitHub code search syntax to know how to search with case-sensitiveness enabled, would have to do so in two separate places (one where the required regex syntax is informed (i.e. `(?-i)`) and when pasting that and see it does not work, he would then have to find again in the documentation how a regex syntax is inputted (i.e. using two slash separators `/(?-i)/`).

### What's being changed (if available, include any code snippets, screenshots, or gifs):

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

2024-11-08 20:07 UTC, nguyenalex836 commented
@nbenitez Thanks so much for opening a PR! I'll get this triaged for review ✨

2024-11-11 09:44 UTC, subatoi requested changes
Hi @nbenitez 👋 I agree we can make improvements here. We should use the opportunity to make this more consistent with the rest of the article, so I've made a suggestion to amend your PR accordingly. 

Thanks for your interest in the GitHub docs!

2024-11-11 09:44 UTC, subatoi commented on content/search-github/github-code-search/understanding-github-code-search-syntax.md
> +By default, code search is case-insensitive. Searching for `True` will include results for _uppercase_ `TRUE` and _lowercase_ `true`. You can do case-sensitive searches by using a regular expression
````suggestion
By default, code search is case-insensitive, and results will include both uppercase and lowercase results. You can do case-sensitive searches by using a regular expression with case insensitivity turned off. For example, to search for the string "True",  you would use:

```text
/(?-i)True/
```
````

2024-11-11 13:38 UTC, subatoi approved these changes, later dismissed
Thank you! I'll get this merged now 👍

2024-11-11 13:38 UTC, subatoi commented on content/search-github/github-code-search/understanding-github-code-search-syntax.md
> +By default, code search is case-insensitive, and results will include both uppercase and lowercase results. You can do case-sensitive searches by using a regular expression with case insensitivity tu
```suggestion
By default, code search is case-insensitive, and results will include both uppercase and lowercase results. You can do case-sensitive searches by using a regular expression with case insensitivity turned off. For example, to search for the string "True", you would use:
```

Just removing a bit of extra whitespace introduced by mistake

2024-11-11 13:39 UTC, subatoi approved these changes

2024-11-11 13:48 UTC, merged