Update transferring-ownership-of-an-oauth-app.md
github/docs pull request #3656
Opened 2021-02-12 23:14 UTC by Muftaa

### Why:

**Closes [issue link]**

### What's being changed:

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-02-13 07:42 UTC, jocelynaddy approved these changes

2021-02-14 01:15 UTC, chienthanking91 approved these changes

2021-02-14 01:55 UTC, jocelynaddy commented on content/developers/apps/transferring-ownership-of-an-oauth-app.md
> +Welcome to NA225: Transferring ownership of an OAuth App
Jocelynaddy@gmail.com

2021-02-14 01:55 UTC, jocelynaddy commented on content/developers/apps/transferring-ownership-of-an-oauth-app.md
>    - /apps/building-integrations/managing-oauth-apps/transferring-ownership-of-an-oauth-app/
Owner jocelynaddy 
/pay me.paypal.jocelynaddy@gmail.com

2021-02-14 03:54 UTC, jocelynaddy requested changes

2021-02-14 03:54 UTC, jocelynaddy commented on content/developers/apps/transferring-ownership-of-an-oauth-app.md
>    - /apps/building-integrations/managing-oauth-apps/transferring-ownership-of-an-oauth-app/
Dystanie Gibson 
Jocelynaddy@gmail.com
Paypal.jocelynaddy@gmail.com
Owners jocelynaddy

2021-02-16 22:51 UTC, closed without merging

2021-02-16 23:01 UTC, herackovalucka commented
Dne út 16. 2. 2021 23:51 uživatel Janice <notifications@github.com> napsal:

> Closed #3656 <https://github.com/github/docs/pull/3656>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/docs/pull/3656#event-4338612874>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASTKCJUFNGBY4TPLW3OAZKDS7LZIVANCNFSM4XRPLTXA>
> .
>

2021-02-16 23:04 UTC, khdijh535 commented
#3666