Add keyboard shortcut for toggling annotations
github/docs pull request #3899
Opened 2021-02-22 19:30 UTC by aaron-tdouble

### Why:

The Special Projects team recently released a feature that allows a user the ability to toggle all diff annotations via the `a` hotkey across all files, similar to the way that `i` does for comments.

This change adds the hotkey to the docs to increase exposure of this new ability.

Issue:  https://github.com/github/special-projects/issues/89
Merged github PR: https://github.com/github/github/pull/171199

**Closes [issue link]**

### What's being changed:

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-02-23 08:55 UTC, Devilishhh approved these changes

2021-02-23 13:46 UTC, aaron-tdouble commented
@Devilishhh thanks for the approval.  The PR is still showing as needing at least one approval which is weird (since you obviously approved).  What do I need to do in order to allow this to be merged?

2021-02-23 14:27 UTC, Devilishhh requested changes
This needs to be merged

2021-02-23 14:28 UTC, Devilishhh commented
> @Devilishhh thanks for the approval.  The PR is still showing as needing at least one approval which is weird (since you obviously approved).  What do I need to do in order to allow this to be merged?

Needs to be merged by someone that is authorised to do so

2021-02-23 21:08 UTC, janiceilene commented
@aaron-tdouble Thanks so much for opening a PR and an issue! I'll get this triaged for writer review ⚡ 

In the future, could you open an issue in [docs content](https://github.com/github/docs-content/issues/new?assignees=&labels=%5B%22Improve+existing+docs%22%5D&template=improve-existing-docs.md&title=)? That'll give writers an opportunity to weigh in on what changes will be needed (that plan is outlined in https://github.com/github/docs-team/issues/340#issuecomment-769974718).

2021-02-26 16:42 UTC, janiceilene approved these changes
This change looks great!

2021-02-26 16:48 UTC, nenehulc requested changes

2021-02-26 16:48 UTC, nenehulc commented on content/github/getting-started-with-github/keyboard-shortcuts.md
> +|<kbd>a</kbd> | Show or hide annotations on diffs
``

2021-02-26 17:37 UTC, merged

2021-02-27 17:37 UTC, nenehulc commented
Wooow

2021-02-27 17:41 UTC, Devilishhh reviewed
All good

2021-03-02 17:27 UTC, Irahaze5 approved these changes

2021-03-02 17:27 UTC, Irahaze5 approved these changes