CommunityBridge is LFX Mentorship now
github/docs pull request #3928
Opened 2021-02-23 16:14 UTC by idvoretskyi

Fixes https://github.com/github/docs/issues/3241

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

2021-02-23 20:56 UTC, ethanpalm requested changes
Thanks for opening this PR! The syntax for this sponsor badge is remaining the same, so I made one small comment. With that change, we should be ready to merge 🚀  😄

2021-02-23 20:56 UTC, ethanpalm commented on content/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository.md
> +[LFX Mentorship (formerly CommunityBridge)](https://lfx.linuxfoundation.org/tools/mentorship) | `lfx_mentorship: PROJECT-NAME`
```suggestion
[LFX Mentorship (formerly CommunityBridge)](https://lfx.linuxfoundation.org/tools/mentorship) | `community_bridge: PROJECT-NAME`
```

The syntax for this badge is remaining the same, so we won't need to change it in this PR.

2021-02-25 14:04 UTC, idvoretskyi commented
@ethanpalm addressed, thanks!

2021-02-25 15:45 UTC, ethanpalm approved these changes

2021-02-25 15:45 UTC, ethanpalm commented
@idvoretskyi thanks for making that change! This looks great and I'll get it merged as soon as all checks are passing ✨

2021-02-25 16:25 UTC, merged