Add information about steps required before importing your migrated data.
github/docs pull request #4007
Opened 2021-02-26 04:10 UTC by kwacky1

### Why:

If you land on this page from a search, there is no indication that prior steps are required.

https://github.com/github/docs-content/issues/3032

### What's being changed:

A small preamble is added before the process that mentions and links to the previous steps

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-02-26 09:16 UTC, felicitymay requested changes
Thanks for raising this PR. It's a good call to add this extra context to the start of this procedure for people who arrive from a search ✨ 

There's one change needed to bring this into line with our localization guidelines. Otherwise this looks like a great change.

You can see your changes on staging here: https://docs-4007--kwacky1-migration-c.herokuapp.com/en/enterprise-server@3.0/admin/user-management/migrating-data-to-your-enterprise.

2021-02-26 09:16 UTC, felicitymay commented on content/admin/user-management/migrating-data-to-your-enterprise.md
> +    * Your [Migration GUID](/admin/user-management/preparing-to-migrate-data-to-your-enterprise).
To simplify localization, wherever possible we avoid inline links.

```suggestion
    * Your Migration GUID. For more information, see "[Preparing to migrate data to your enterprise](/admin/user-management/preparing-to-migrate-data-to-your-enterprise)."
```

2021-02-28 18:14 UTC, sartgoo commented
team-review-requested:[TEAMNAME4007[USERNAME]

2021-03-01 09:06 UTC, felicitymay approved these changes
Thanks. This looks ready to merge once the repository is unfrozen (should be today).

2021-03-01 22:13 UTC, merged