Update about-pull-requests.md
github/docs pull request #483
Opened 2020-10-13 12:31 UTC by Ruth-ikegah

### Why:

This PR fixes #430 

### What's being changed:
A section has been added about clarifying the difference in the commits displayed shown on the compare page and what's shown on a pull request page.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-13 12:46 UTC, Bocoi501 approved these changes

2020-10-13 12:54 UTC, Bocoi501 requested changes

2020-10-13 12:54 UTC, Bocoi501 commented on content/github/collaborating-with-issues-and-pull-requests/about-pull-requests.md
> +### Difference between commits on Compare page and Pull Request page
### Further reading

- "[Pull request](/articles/github-glossary/#pull-request)" in the {% data variables.product.prodname_dotcom %} glossary

2020-10-13 23:44 UTC, janiceilene commented
Thanks @Ruth-ikegah! I'll get this triaged for review ⚡

2020-10-15 15:49 UTC, felicitymay requested changes
👋🏻 Hi @Ruth-ikegah, thanks for adding this information 😄 

It looks as if the issue you were working from was transferred from a really old (2017) internal issue. This was before we started localizing content so the suggested text was out of line with our current recommendations. I've made suggestions to bring it into line.

2020-10-15 15:49 UTC, felicitymay commented on content/github/collaborating-with-issues-and-pull-requests/about-pull-requests.md
> +Compare pages show a compare between the tip of the head ref and the current common ancestor (i.e. merge base) of the head and base ref. On the other hand, pull request pages show a compare between t
Changes suggested to make this easier for people to read if English isn't their first language.

```suggestion
The compare and pull request pages use different methods to calculate the diff for changed files:

- Compare pages show the diff between the tip of the head ref and the current common ancestor (that is, the merge base) of the head and base ref. 
- Pull request pages show the diff between the tip of the head ref and the common ancestor of the head and base ref at the time when the pull request was created. Consequently, the merge base used for the comparison might be different.
```

2020-10-15 17:29 UTC, Ruth-ikegah commented
> 👋🏻 Hi @Ruth-ikegah, thanks for adding this information 😄
> 
> It looks as if the issue you were working from was transferred from a really old (2017) internal issue. This was before we started localizing content so the suggested text was out of line with our current recommendations. I've made suggestions to bring it into line.

Thanks for this amazing review @felicitymay I really learnt a lot. I have applied the suggested changes. Thanks.

2020-10-15 21:03 UTC, felicitymay approved these changes
I'm really glad you found the review helpful ✨ 

This looks ready to merge once the tests pass on the updated branch.

I've just noticed from your profile that you're a fellow technical writer. We're a fairly rare species, so it's particularly lovely to meet you 😄

2020-10-15 21:11 UTC, merged

2020-10-15 21:11 UTC, Ruth-ikegah commented
> I'm really glad you found the review helpful ✨
> 
> This looks ready to merge once the tests pass on the updated branch.
> 
> I've just noticed from your profile that you're a fellow technical writer. We're a fairly rare species, so it's particularly lovely to meet you 😄

Thanks! It is a pleasure meeting you too. I hope to learn more from you. Is there a community chat for @github docs yet?

2020-10-15 21:13 UTC, felicitymay commented
> Is there a community chat for @github docs yet?

That's a great question and I don't know the answer. I'll pass it on to the person who's leading the open source initiative ✨

2020-10-15 21:20 UTC, janiceilene commented
👋 @Ruth-ikegah! I'm talking about open sourcing the docs during [Open Source Friday](https://twitter.com/github/status/1316734829367635972) tomorrow! Is that what you're referring to or something else? I'm definitely interested in hearing about what you think would be helpful for folks!

2020-10-15 21:28 UTC, Ruth-ikegah commented
> 👋 @Ruth-ikegah! I'm talking about open sourcing the docs during [Open Source Friday](https://twitter.com/github/status/1316734829367635972) tomorrow! Is that what you're referring to or something else? I'm definitely interested in hearing about what you think would be helpful for folks!

Nice I just registered, will be attending. I was referring to something like a community chat channel where contributors of Github docs can network and share ideas.