Update configuring-rubygems-for-use-with-github-packages.md
github/docs pull request #5313
Opened 2021-04-13 03:18 UTC by mesca216

### Why:

**Closes [issue link]**

### What's being changed:

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-04-13 06:26 UTC, glitterblondie reviewed
(Y)

2021-04-14 16:56 UTC, janiceilene commented
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

2021-04-14 17:16 UTC, danna527 commented
Приветствую вас я не изменяла мойим телефонах и моим сайты чужие люди пользуется вот уже несколько месяцев хакеры взломали и пользуется я менла симку телефон без полезно . по этому я хотела учиться у вас 


--
Отправлено из Mail.ru для Android среда, 14 апреля 2021г., 19:56 +03:00 от Janice  ***@***.*** :

>Thanks for opening a PR 👍 Please fill out the  pull request template in the top comment in this pull request, then we'll get this up for review!
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-04-15 11:05 UTC, RattaphonKarnsomlap commented
(Y)

2021-04-15 11:06 UTC, RattaphonKarnsomlap requested changes
P

2021-04-19 06:55 UTC, Siwy47 approved these changes

2021-04-19 21:48 UTC, closed without merging

2021-04-20 21:55 UTC, mesca216 commented
@mesca216 `1`

> 

> #
Duplicate of #