Add `pull_request_target` in base_ref and head_ref doc
github/docs pull request #5392
Opened 2021-04-15 06:52 UTC by Yikun

The `github.head_ref` and `github.base_ref` are available when the event that triggers a workflow run are `pull_request` and `pull_request_target`.

2021-04-15 08:47 UTC, RattaphonKarnsomlap approved these changes

2021-04-15 10:09 UTC, RattaphonKarnsomlap approved these changes

2021-04-15 10:12 UTC, RattaphonKarnsomlap reviewed
"pull_request"

2021-04-15 10:12 UTC, RattaphonKarnsomlap commented on content/actions/reference/context-and-expression-syntax-for-github-actions.md
> -| `github.base_ref` | `string` | The `base_ref` or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is a `pull_request`
"pull_request"

2021-04-15 10:24 UTC, RattaphonKarnsomlap requested changes

2021-04-15 10:24 UTC, RattaphonKarnsomlap commented on content/actions/reference/context-and-expression-syntax-for-github-actions.md
> -| `github.base_ref` | `string` | The `base_ref` or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is a `pull_request`
| `github.base_ref` | `string` | The `base_ref` or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run are `pull_request` and `pull_request_target`. |

2021-04-15 10:26 UTC, RattaphonKarnsomlap requested changes

2021-04-15 10:26 UTC, RattaphonKarnsomlap commented on content/actions/reference/context-and-expression-syntax-for-github-actions.md
> -| `github.head_ref` | `string` | The `head_ref` or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is a `pull_request`
| `github.head_ref` | `สตริง` | "head_ref" หรือสาขาต้นทางของคำขอดึงในเวิร์กโฟลว์ที่เรียกใช้ คุณสมบัตินี้จะพร้อมใช้งานก็ต่อเมื่อเหตุการณ์ที่ทริกเกอร์การรันเวิร์กโฟลว์คือ `pull_request 'และ` pull_request_target ' |

2021-04-15 10:30 UTC, RattaphonKarnsomlap requested changes
P

2021-04-16 21:37 UTC, janiceilene commented
@Yikun Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

2021-04-17 01:13 UTC, Yikun commented
@janiceilene updated

2021-04-19 21:15 UTC, janiceilene commented
@Yikun Thanks so much for opening an issue and filling out the PR template! I'll get this triaged for review ⚡

2021-04-20 06:11 UTC, dow572 approved these changes, later dismissed

2021-04-20 06:15 UTC, nelsondani commented
****_34000_****

2021-04-25 13:30 UTC, VChernomYA approved these changes

2021-05-11 06:04 UTC, lucascosti approved these changes, later dismissed
Thanks for this change, @Yikun! I've made a minor wording change, but otherwise this looks great.

2021-05-11 06:04 UTC, lucascosti commented on content/actions/reference/context-and-expression-syntax-for-github-actions.md
> +| `github.base_ref` | `string` | The `base_ref` or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run are `pull_request`
```suggestion
| `github.base_ref` | `string` | The `base_ref` or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either `pull_request` or `pull_request_target`. |
```

2021-05-11 06:04 UTC, lucascosti commented on content/actions/reference/context-and-expression-syntax-for-github-actions.md
> +| `github.head_ref` | `string` | The `head_ref` or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run are `pull_request`
```suggestion
| `github.head_ref` | `string` | The `head_ref` or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either `pull_request` or `pull_request_target`. |
```

2021-05-11 06:13 UTC, lucascosti approved these changes

2021-05-11 06:13 UTC, merged

2021-05-21 00:09 UTC, dow572 reviewed
Cogency