Fixed broken links in README.md
github/docs pull request #550
Opened 2020-10-15 10:17 UTC by Anita-ihuman

### Why:
The existing links on the README.md for contributing guide and makeup reference guide were all throwing error 404 page not found.

### What's being changed:
This PR is a fix for issue no #524 and #525. It takes care of the broken links for the contributing guide and the makeup reference guide.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-15 22:29 UTC, janiceilene requested changes
Thank you so much for fixing these links @Anita-ihuman 🎉 I made two small suggestions to make these into internal links so the links will still work on folks' forks. Once you accept those suggestions, I'll get this merged in 💖

2020-10-15 22:29 UTC, janiceilene commented on content/README.md
> +See the [markup reference guide](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md) for more information about supported Markdown features.
```suggestion
See the [markup reference guide](/contributing/content-markup-reference.md) for more information about supported Markdown features.
```

2020-10-15 22:29 UTC, janiceilene commented on content/README.md
> +See the [contributing docs](https://github.com/github/docs/blob/main/CONTRIBUTING.md) for general information about working with the docs.
```suggestion
See the [contributing docs](/CONTRIBUTING.md) for general information about working with the docs.
```

2020-10-16 09:13 UTC, Anita-ihuman reviewed
Yeah, Thank you for pointing out.

2020-10-18 20:25 UTC, Anita-ihuman reviewed
I have seen the suggestions

2020-10-19 23:47 UTC, janiceilene commented
This looks great @Anita-ihuman, thank you so much! I'll get this branch updated and merged once tests are passing 💖

2020-10-19 23:47 UTC, janiceilene approved these changes

2020-10-20 00:03 UTC, merged