Update https-cloning-errors.md
github/docs pull request #553
Opened 2020-10-15 11:42 UTC by casals

### Why:

Partially fixes #429 

### What's being changed:

Fixed the existing documentation on HTTPS Cloning Errors and Cached Credentials to include the author's suggestion. Since "incorrect or out of date credentials cached" depends on the developer choosing to use password caching, I opted for extending the existing tip note instead of complementing the introductory paragraph (just to keep things within the same context). 

Please note that this PR only fixes one of the possible three alterations required by this issue, as described/proposed [in this comment](https://github.com/github/docs/issues/429#issuecomment-709217217).

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-16 02:56 UTC, janiceilene commented
👋 Thanks @casals! I'll get this triaged for review 🎉

2020-10-21 18:02 UTC, felicitymay requested changes
Hi @casals - thanks for your analysis of the related issue. 💎 

Your suggestion of including the troubleshooting information in the tip seems good. I've made a small suggestion to the text, but otherwise this looks ready to merge.

2020-10-21 22:10 UTC, felicitymay approved these changes

2020-10-21 22:11 UTC, felicitymay commented
Thanks for raising the two new issues for the remaining work on this issue 😄

2020-10-21 22:11 UTC, merged