Update Line 2
github/docs pull request #5619
Opened 2021-04-22 00:00 UTC by kleeadrian

The title just said Continuous Integration whereas the blurb below says Continuous Integration and Continuous Deployment.

### Why:

**Closes [issue link]**

### What's being changed:

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2021-04-22 04:30 UTC, APA2527 approved these changes

2021-04-22 07:20 UTC, schmelto approved these changes

2021-04-23 22:14 UTC, janiceilene commented
@kleeadrian Thanks so much for opening a PR! I'll get this triaged for review 🎉

2021-04-27 23:00 UTC, loida24 reviewed
TitleChange`

2021-04-28 21:43 UTC, skedwards88 requested changes
This change makes sense! However, to pass the CI tests, you will need to rename the file to match the new title. Additionally, so that the old link still works for users, you will want to add the old file name to the `redirect_from` list in the YAML front matter (line 5).

2021-05-01 12:36 UTC, jorgetron commented on content/actions/guides/about-continuous-integration.md
>  ---
n p

2021-05-06 20:04 UTC, janiceilene commented
@kleeadrian I'm going to close this for now, but if you'd like to make the changes suggested in https://github.com/github/docs/pull/5619#pullrequestreview-647664536, feel free to reopen!

2021-05-06 20:04 UTC, closed without merging

2021-07-17 13:53 UTC, ryanendo reviewed
#8319

2022-09-17 08:04 UTC, KaAwatea commented
> The title just said Continuous Integration whereas the blurb below says Continuous Integration and Continuous Deployment.
> 
> ### Why:
> **Closes [issue link]**
> 
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

Why are you stealing my repositories