Update secret-scanning.md to add more 'gotcha' information
github/docs pull request #5637
Opened 2021-04-22 17:20 UTC by just-joshing

### Why:

We received partner feedback that they encountered difficulty implementing signature validation because it wasn't clear that the raw payload needed to be used.

They use IBM Cloud Functions Actions which by default parse JSON request payloads.
So when they would stringify the JSON again and find signature validation was failing, it wasn't clear that the issue was stringifying the JSON again rearranged key/value members and changed spacing.

### What's being changed:

This change updates:
- the sample JSON payloads to have no spaces, like production
- the URL for getting the public key in the samples which was pointing to the old endpoint `token_scanning`
- the first token sample to only include a token, not `X-Header-Banner` as well which wouldn't be included in a payload

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

2021-04-22 18:07 UTC, just-joshing commented
cc @github/dsp-token-scanning-reviewers

2021-04-22 18:11 UTC, greysteil approved these changes, later dismissed

2021-04-22 18:19 UTC, aashah submitted a review, later dismissed
neat

2021-04-22 18:22 UTC, aashah commented on content/developers/overview/secret-scanning.md
> +**Note**: When you send a request to the public key endpoint above, you may hit rate limits. To avoid hitting rate limits, you can use a personal access token (no scopes required) as suggested in the
Edit: they do have it...nevermind

2021-04-22 18:24 UTC, just-joshing commented on content/developers/overview/secret-scanning.md
> +**Note**: When you send a request to the public key endpoint above, you may hit rate limits. To avoid hitting rate limits, you can use a personal access token (no scopes required) as suggested in the
👍

2021-04-22 18:52 UTC, aashah approved these changes
🤙

2021-04-23 04:22 UTC, QbZn requested changes

2021-04-23 04:22 UTC, QbZn commented on content/developers/overview/secret-scanning.md
> -**Note**: When you send a request to the public key endpoint above, you may hit rate limits. To avoid hitting rate limits, you can use a personal access token as suggested below, or use a conditional
b******0@gmail.com

2021-04-23 22:32 UTC, janiceilene commented
@just-joshing Thanks so much for opening a PR! I'll get this triaged for review ⚡

2021-04-26 17:46 UTC, greysteil approved these changes

2021-04-28 22:11 UTC, skedwards88 approved these changes
🎉 Thank you for opening this PR! I'll get these changes merged down for you.

2021-04-28 22:19 UTC, merged