exclusion is not supported by notification filters
github/docs pull request #692
Opened 2020-10-21 16:02 UTC by mchelen-gov

### Why:

### What's being changed:

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-21 18:53 UTC, deril1 requested changes
content/github/managing-subscriptions-and-notifications-on-github/managing-notifications-from-your-inbox.md

2020-10-23 22:09 UTC, janiceilene commented
Thanks so much @mchelen-gov! I'll get this triaged for review 🌟

2020-10-27 11:32 UTC, hubwriter commented on content/github/managing-subscriptions-and-notifications-on-github/managing-notifications-from-your-inbox.md
> +  - Search [exclusion](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/understanding-the-search-syntax#exclude-certain-results) using `NOT` or `-QUALIFIER`.
Many thanks for adding this.

To accommodate page versioning, we leave off the first part of URLs in links to other GitHub docs pages: 
```suggestion
  - Search [exclusion](/github/searching-for-information-on-github/understanding-the-search-syntax#exclude-certain-results) using `NOT` or `-QUALIFIER`.
```

2020-10-27 11:33 UTC, hubwriter requested changes
@mchelen-gov - Thanks for taking the time to submit this pull request. We really appreciate your help improving GitHub documentation. I've suggested a small change. Thanks again. 👍

2020-11-02 15:21 UTC, mchelen-gov commented
commit suggestion, thanks!

2020-11-04 09:03 UTC, hubwriter approved these changes

2020-11-04 09:27 UTC, hubwriter commented
Thanks @mchelen-gov - merging this now.

2020-11-04 09:27 UTC, merged