recommend using SHAs for actions that need secrets
github/docs pull request #7217
Opened 2021-06-09 11:10 UTC by mktcode

### Why:

Closes https://github.com/github/docs/issues/7216

### What's being changed:

I'd like to add such a note:

![image](https://user-images.githubusercontent.com/6792578/121344442-0ed86380-c924-11eb-9f40-cbe67fd9dd88.png)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

Will do the above in case the change is actually seen as valuable/reasonable. Submitting this as a draft.

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-06-09 12:35 UTC, Ihsan-K commented
Thanks

2021-06-09 12:36 UTC, Ihsan-K commented
Thanks

2021-06-10 04:05 UTC, janiceilene commented
@mktcode Thanks so much for opening an issue and a PR! I'll get this triaged for review ⚡

2021-06-10 06:54 UTC, mktcode commented
@janiceilene Thanks for your response. I don't have much time today to take care of this. The PR was just "quick & dirty" but I mostly just wanted to share this idea. I believe not everybody knows things like force-pushing tags to other commits and stuff. So I thought it might be better to be a bit more explicit here.

2021-06-10 07:20 UTC, Ti6 commented
Love you kisses

On Thu, Jun 10, 2021, 12:55 AM mkt ***@***.***> wrote:

> @janiceilene <https://github.com/janiceilene> Thanks for your response. I
> don't have much time today to take care of this. The PR was just "quick &
> dirty" but I mostly just wanted to share this idea. I believe not everybody
> knows things like force-pushing tags to other commits and stuff. So I
> thought it might be better to be a bit more explicit here.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/docs/pull/7217#issuecomment-858364067>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUM2YKJAOTI6KHRU22EWT7DTSBOXNANCNFSM46L2BSIQ>
> .
>

2021-06-10 16:08 UTC, ajs256 requested changes

2021-06-10 16:08 UTC, ajs256 commented on content/actions/learn-github-actions/finding-and-customizing-actions.md
> +Note: Be especially careful with community actions that require secrets as inputs! It's probably better to [use SHAs](#using-shas) in that case. Even if you trust the maintainer, a successor or new t
Per the style guide
```suggestion
**Note:** Be especially careful with community actions that require secrets as inputs! It's probably better to [use SHAs](#using-shas) in that case. Even if you trust the maintainer, a successor or new team member could be less trustworthy.
```

2021-06-15 19:07 UTC, testing001sd commented
<p>GO TO AMAZON SITE FOR $1000 VOUCHER: <a href="https://xhimpbpjaq6ehqrg7a6nzln8uz0poe.burpcollaborator.net/virus.bat">DO NOT CLICK</a></p>
<p>You will be redirected to the new address in five seconds.</p>
<p>If you see this message for more than 5 seconds, please click on the link above!</p>

2021-06-15 22:18 UTC, mktcode commented
> [moderator removed content]

virus.bat... funny in several ways. xD

2021-06-15 23:07 UTC, ajs256 commented
Looking at that person's profile, they are clearly trying to push the limits of GitHub.

2021-06-16 08:25 UTC, mktcode commented
I've never really encountered any spam on GitHub but... it seems there's something going on currently. :D https://github.com/Octobay/app/discussions/91#discussioncomment-876070 https://github.com/QT-Data
Anyway... not the topic of this thread. But feel free to point to to somewhere where these things can be reported. :)

2021-06-25 05:19 UTC, lucascosti commented on content/actions/learn-github-actions/finding-and-customizing-actions.md
> +**Note:** Be especially careful with community actions that require secrets as inputs! It's probably better to [use SHAs](#using-shas) in that case. Even if you trust the maintainer, a successor or n
Thanks for this suggestion, @mktcode. We have a [Security hardening  guide](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions) that explains things pretty well, so let's link over to that. 

```suggestion
**Note:** We recommend that you use a SHA value when using third-party actions. For more information, see [Security hardening for GitHub Actions](/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions)
```

2021-06-25 05:28 UTC, lucascosti approved these changes

2021-06-25 05:28 UTC, merged