Update sharing-workflows-with-your-organization.md
github/docs pull request #7301
Opened 2021-06-11 19:52 UTC by MaxFlanders

### Why:

Documentation didn't highlight an important piece of information effectively.

### What's being changed:

Placing a small piece of documentation in a callout box so it stands out more.

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-06-11 20:39 UTC, Syahril92 approved these changes

2021-06-11 20:41 UTC, Syahril92 requested changes
Good n nice

2021-06-11 22:47 UTC, janiceilene commented
@MaxFlanders Thanks so much for opening a PR! I'll get this triaged for review ⚡

2021-06-12 00:25 UTC, ajs256 reviewed
I just added a suggestion to use a callout instead of a blockquote.

2021-06-12 00:25 UTC, ajs256 commented on content/actions/learn-github-actions/sharing-workflows-with-your-organization.md
> +> **Note:** Workflow templates can be used to create new workflows in an organizations' public repositories; to use templates to create workflows in private repositories, the organization must be par
```suggestion
{% note %}
**Note:** Workflow templates can be used to create new workflows in an organizations' public repositories; to use templates to create workflows in private repositories, the organization must be part of an enterprise plan.
{% endnote %}
```

2021-06-12 19:02 UTC, anh1200a approved these changes

2021-06-12 19:03 UTC, anh1200a submitted a review, later dismissed

2021-06-12 19:03 UTC, anh1200a commented on content/actions/learn-github-actions/sharing-workflows-with-your-organization.md
> +> **Note:** Workflow templates can be used to create new workflows in an organizations' public repositories; to use templates to create workflows in private repositories, the organization must be par
Ok

2021-06-12 19:03 UTC, anh1200a reviewed
Okr

2021-06-14 06:40 UTC, mchammer01 commented on content/actions/learn-github-actions/sharing-workflows-with-your-organization.md
> +**Note:** Workflow templates can be used to create new workflows in an organizations' public repositories; to use templates to create workflows in private repositories, the organization must be part
```suggestion

**Note:** Workflow templates can be used to create new workflows in an organization' s public repository; to use templates to create workflows in private repositories, the organization must be part of an enterprise plan.
```

2021-06-14 06:40 UTC, mchammer01 commented on content/actions/learn-github-actions/sharing-workflows-with-your-organization.md
> +{% endnote %}
```suggestion

{% endnote %}
```

2021-06-14 06:47 UTC, mchammer01 approved these changes
@MaxFlanders - LGTM ✨ 
(Made a couple of minor syntax and editorial edits)

2021-06-14 06:55 UTC, merged