Update displaying-verification-statuses-for-all-of-your-commits.md
github/docs pull request #8172
Opened 2021-07-13 16:02 UTC by x10an14

It says cryptographically unverified, when it in fact _is_ cryptographically verified.

I'd suggest Github changes this scenario to `partially verified` at the very least (as opposed to "WARNING! WARNING! UNVERIFIED!", but ideally I'd like to be allowed to set whatever author email I want in my git commits, without that impeding on the veracity of my GPG signatures.

My use-case is to not spread an email I care about more than I have to. Enough trawlers already - few if any care to parse GPG keys and extract (it seems).
9/10 times (in my personal experience) they just trawl github commit logs with a webscraping service instead.

Those who think that they must match (that the git commit/tag author email gives any security at all) have a nasty surprise-in-waiting.

### Why:

Closes [issue link]

### What's being changed:

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-07-14 05:14 UTC, RupeshBhandari requested changes
the claim is valid

2021-07-14 11:51 UTC, ramyaparimi commented
@x10an14 Thanks so much for opening a PR! I'll get this triaged for review :zap:

2021-07-14 14:33 UTC, x10an14 commented
> the claim is valid

? Are you referring to the gpg signature?

2021-07-14 18:30 UTC, Roth386 submitted a review, later dismissed

2021-07-16 11:56 UTC, lecoursen reviewed
Thanks @x10an14! I left a few suggested changes, which I'll apply now, then merge! ⚡

2021-07-16 11:56 UTC, lecoursen commented on content/github/authenticating-to-github/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits.md
> +By default commits and tags are marked "Verified" if they are signed with a GPG or S/MIME key that was successfully verified. If a commit or tag has a signature that can't be verified - or can be cry
Hi @x10an14! When we refer to "verified" in this article, we mean verified by GitHub, which requires the matching email address... not cryptographically verified.

```suggestion
By default commits and tags are marked "Verified" if they are signed with a GPG or S/MIME key that was successfully verified. If a commit or tag has a signature that can't be verified by {% data variables.product.prodname_dotcom %}, we mark the commit or tag "Unverified." In all other cases no verification status is displayed.
```

2021-07-16 11:56 UTC, lecoursen commented on content/github/authenticating-to-github/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits.md
> +You should only enable vigilant mode if you sign all of your commits and tags, and ensure that you _always_ set git commit author email to an (identical) email listed on your GPG primary key when usi
We check the committer address, not the author address.

```suggestion
You should only enable vigilant mode if you sign all of your commits and tags and use an email address that is verified in {% data variables.product.product_name %} for your committer email address. After enabling this mode, any unsigned commits or tags that you generate locally and push to {% data variables.product.prodname_dotcom %} will be marked "Unverified."
```

2021-07-16 11:58 UTC, lecoursen commented on content/github/authenticating-to-github/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits.md
> +You should only enable vigilant mode if you sign all of your commits and tags and use an email address that is verified in {% data variables.product.product_name %} for your committer email address.
```suggestion
You should only enable vigilant mode if you sign all of your commits and tags and use an email address that is verified for your account on {% data variables.product.product_name %} as your committer email address. After enabling this mode, any unsigned commits or tags that you generate locally and push to {% data variables.product.prodname_dotcom %} will be marked "Unverified."
```

2021-07-16 11:58 UTC, lecoursen approved these changes

2021-07-16 12:17 UTC, merged

2021-07-16 13:15 UTC, x10an14 commented
I'm sorry, but I don't think you've solved the core of the issue here. Is this perhaps not the right place to come with this customer feedback?

Users will look at "Vigilant" and see the "verified/unverified" tags - and act/react on a basis if something seems "verified and safe" vs "unverified and unsafe".
And only the fewest users will care to git clone the commits themselves, and double-check the GPG commit signature themselves - when and if your "Vigilant" system marks a commit as "unverified".

In essence, I get the UX that you're hiding/diminishing the value of a "cryptographically verifiable signature" in your efforts to promote the Github's vendor-specific "Vigilant".

My commits (pushed to github) will still be marked as "unverified", and that's doing _me_ a disservice since I've gone through the trouble of learning GPG, handling my keys securely with smart-cards, and signing my commits so people can trust that _this is *me*_.

Not some random rootkit on my machine or random mischievous agent on the internet.

I don't mind Github wanting to promote/make use of "Vigilant", but why does it need to react when these two emails don't match? Given that the cryptographic signature is valid???

2021-07-16 13:22 UTC, x10an14 commented
Re-reading your edits to the proposed changes, I see that I actually _am_ fulfilling all requirements. Yet my commits get marked "Unverified".

Just see [here](https://github.com/maxjacobson/vim-fzf-coauthorship/pull/2/commits/f1c693d360931a058a8d73140949e77cc9598128).

> By default commits and tags are marked "Verified" if they are signed with a GPG or S/MIME key that was successfully verified. If a commit or tag has a signature that can't be verified by {% data variables.product.prodname_dotcom %}, we mark the commit or tag "Unverified." In all other cases no verification status is displayed.

It is cryptographically verifiable.

> You should only enable vigilant mode if you sign all of your commits and tags and use an email address that is verified for your account on {% data variables.product.product_name %} as your committer email address.

But both my committer (AND GPG email) are verified with you (read: Github) - so why are my commits marked as unverified then?

The only thing I can see (but there might be something I don't see) is that you (for some unfathomable reason to me) compare the committer email with the emails listed in the GPG key.

2021-07-22 12:13 UTC, ramyaparimi commented
@x10an14 This is great feedback to give to https://support.github.com/contact/feedback :yellow_heart: