chore: Pull JS Linting to separate Action
github/docs pull request #862
Opened 2020-10-28 01:00 UTC by nschonni

### Why:

### What's being changed:

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-10-28 22:39 UTC, janiceilene commented
Thanks @nschonni! I'll get this triaged for review ⚡

2020-10-29 15:02 UTC, heiskr approved these changes
👏🏼 This looks like a solid improvement.

2020-11-03 01:20 UTC, JamesMGreene requested changes
I love what this change achieves. 😍 

However, I believe this _also_ implies that we will be unable to make the linting job be a **required check** for merging into the `main` branch, which is less desirable. 😕 

I'll confirm with the Actions support folks internally but I'm going to block this PR for now by marking my review as "Request changes". 🛑

2020-11-03 01:30 UTC, nschonni commented
No problem, if this way doesn't work, I can try and re-work it with fkirc/skip-duplicate-actions

2020-11-03 21:42 UTC, nschonni commented
@JamesMGreene figured out a way to test it by removing the trigger on the config change, and it looks like it will stall with the "Required".

![image](https://user-images.githubusercontent.com/1297909/98043634-8cb71800-1df3-11eb-8d37-ecb7d262098e.png)

I'll try with the other action, and do the same for https://github.com/github/docs/pull/541

2020-11-03 22:00 UTC, nschonni commented
@JamesMGreene I can't see if the now "Skipped" required check will block the commit. Can you let me know, and I can in-line the skip check flow into the `lint` job instead

2020-11-04 15:24 UTC, JamesMGreene approved these changes
Approving to check if it meets "Required Checks"... uhh... requirements. 😅

2020-11-04 15:28 UTC, nschonni commented
Oops, looks like the branch merge triggered the `lint` check. I'll rebase back to the first commit and re-submit the second one to see if we can get back to the "Skipped" required check

2020-11-04 15:58 UTC, nschonni commented
@JamesMGreene OK, it's back to the "Skipped" required check again

2020-11-04 16:06 UTC, JamesMGreene commented on .github/workflows/js-lint.yml
> +          paths: '["**/*.js","package*.json",".github/workflows/js-lint.yml"]'
Let's add some spaces here for legibility. ✨ 

```suggestion
          paths: '["**/*.js", "package*.json", ".github/workflows/js-lint.yml"]'
```

2020-11-04 16:07 UTC, JamesMGreene approved these changes
Good news! ☝🏻  It actually seems to be happy with this. 🎉 

![image](https://user-images.githubusercontent.com/417751/98135041-02b78f80-1e85-11eb-9fbb-cdf9fcbd689c.png)

That's so awesome, @nschonni. It really cleans the test workflow up nicely. 😍

2020-11-04 16:09 UTC, merged