Adds a Images section to Basic Writing and Formatting Syntax
github/docs pull request #8982
Opened 2021-08-12 07:42 UTC by thispsj

### Why:

Closes #8964 

### What's being changed:

Adds images section to [this article](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

2021-08-12 11:21 UTC, ramyaparimi commented
@thispsj 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

2021-08-14 02:17 UTC, Zringgo77 commented
> ### Why:
> Closes #8964
> 
> ### What's being changed:
> Adds images section to [this article](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
> * [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

2021-08-14 23:22 UTC, WALEEDANAM requested changes
content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
[AdsTxtAggregationDataAgreement2018.pdf](https://github.com/github/docs/files/6987290/AdsTxtAggregationDataAgreement2018.pdf)

2021-08-15 01:14 UTC, Benny1Blanco commented
/**
 *Submitted for verification at Etherscan.io on 2021-04-04
*/

// File: @openzeppelin/contracts/math/SafeMath.sol

// SPDX-License-Identifier: MIT

pragma solidity >=0.6.0 <0.8.0;

/**
 * @dev Wrappers over Solidity's arithmetic operations with added overflow
 * checks.
 *
 * Arithmetic operations in Solidity wrap on overflow. This can easily result
 * in bugs, because programmers usually assume that an overflow raises an
 * error, which is the standard behavior in high level programming languages.
 * `SafeMath` restores this intuition by reverting the transaction when an
 * operation overflows.
 *
 * Using this library instead of the unchecked operations eliminates an entire
 * class of bugs, so it's recommended to use it always.
 */
library SafeMath {
    /**
     * @dev Returns the addition of two unsigned integers, with an overflow flag.
     *
     * _Available since v3.4._
     */
    function tryAdd(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        uint256 c = a + b;
        if (c < a) return (false, 0);
        return (true, c);
    }

    /**
     * @dev Returns the substraction of two unsigned integers, with an overflow flag.
     *
     * _Available since v3.4._
     */
    function trySub(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        if (b > a) return (false, 0);
        return (true, a - b);
    }

    /**
     * @dev Returns the multiplication of two unsigned integers, with an overflow flag.
     *
     * _Available since v3.4._
     */
    function tryMul(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
        // benefit is lost if 'b' is also tested.
        // See: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/522
        if (a == 0) return (true, 0);
        uint256 c = a * b;
        if (c / a != b) return (false, 0);
        return (true, c);
    }

    /**
     * @dev Returns the division of two unsigned integers, with a division by zero flag.
     *
     * _Available since v3.4._
     */
    function tryDiv(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        if (b == 0) return (false, 0);
        return (true, a / b);
    }

    /**
     * @dev Returns the remainder of dividing two unsigned integers, with a division by zero flag.
     *
     * _Available since v3.4._
     */
    function tryMod(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        if (b == 0) return (false, 0);
        return (true, a % b);
    }

    /**
     * @dev Returns the addition of two unsigned integers, reverting on
     * overflow.
     *
     * Counterpart to Solidity's `+` operator.
     *
     * Requirements:
     *
     * - Addition cannot overflow.
     */
    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a + b;
        require(c >= a, "SafeMath: addition overflow");
        return c;
    }

    /**
     * @dev Returns the subtraction of two unsigned integers, reverting on
     * overflow (when the result is negative).
     *
     * Counterpart to Solidity's `-` operator.
     *
     * Requirements:
     *
     * - Subtraction cannot overflow.
     */
    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        require(b <= a, "SafeMath: subtraction overflow");
        return a - b;
    }

    /**
     * @dev Returns the multiplication of two unsigned integers, reverting on
     * overflow.
     *
     * Counterpart to Solidity's `*` operator.
     *
     * Requirements:
     *
     * - Multiplication cannot overflow.
     */
    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        if (a == 0) return 0;
        uint256 c = a * b;
        require(c / a == b, "SafeMath: multiplication overflow");
        return c;
    }

    /**
     * @dev Returns the integer division of two unsigned integers, reverting on
     * division by zero. The result is rounded towards zero.
     *
     * Counterpart to Solidity's `/` operator. Note: this function uses a
     * `revert` opcode (which leaves remaining gas untouched) while Solidity
     * uses an invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function div(uint256 a, uint256 b) internal pure returns (uint256) {
        require(b > 0, "SafeMath: division by zero");
        return a / b;
    }

    /**
     * @dev Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
     * reverting when dividing by zero.
     *
     * Counterpart to Solidity's `%` operator. This function uses a `revert`
     * opcode (which leaves remaining gas untouched) while Solidity uses an
     * invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function mod(uint256 a, uint256 b) internal pure returns (uint256) {
        require(b > 0, "SafeMath: modulo by zero");
        return a % b;
    }

    /**
     * @dev Returns the subtraction of two unsigned integers, reverting with custom message on
     * overflow (when the result is negative).
     *
     * CAUTION: This function is deprecated because it requires allocating memory for the error
     * message unnecessarily. For custom revert reasons use {trySub}.
     *
     * Counterpart to Solidity's `-` operator.
     *
     * Requirements:
     *
     * - Subtraction cannot overflow.
     */
    function sub(uint256 a, uint256 b, string memory errorMessage) internal pure returns (uint256) {
        require(b <= a, errorMessage);
        return a - b;
    }

    /**
     * @dev Returns the integer division of two unsigned integers, reverting with custom message on
     * division by zero. The result is rounded towards zero.
     *
     * CAUTION: This function is deprecated because it requires allocating memory for the error
     * message unnecessarily. For custom revert reasons use {tryDiv}.
     *
     * Counterpart to Solidity's `/` operator. Note: this function uses a
     * `revert` opcode (which leaves remaining gas untouched) while Solidity
     * uses an invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function div(uint256 a, uint256 b, string memory errorMessage) internal pure returns (uint256) {
        require(b > 0, errorMessage);
        return a / b;
    }

    /**
     * @dev Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
     * reverting with custom message when dividing by zero.
     *
     * CAUTION: This function is deprecated because it requires allocating memory for the error
     * message unnecessarily. For custom revert reasons use {tryMod}.
     *
     * Counterpart to Solidity's `%` operator. This function uses a `revert`
     * opcode (which leaves remaining gas untouched) while Solidity uses an
     * invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function mod(uint256 a, uint256 b, string memory errorMessage) internal pure returns (uint256) {
        require(b > 0, errorMessage);
        return a % b;
    }
}

// File: @openzeppelin/contracts/token/ERC20/IERC20.sol



pragma solidity >=0.6.0 <0.8.0;

/**
 * @dev Interface of the ERC20 standard as defined in the EIP.
 */
interface IERC20 {
    /**
     * @dev Returns the amount of tokens in existence.
     */
    function totalSupply() external view returns (uint256);

    /**
     * @dev Returns the amount of tokens owned by `account`.
     */
    function balanceOf(address account) external view returns (uint256);

    /**
     * @dev Moves `amount` tokens from the caller's account to `recipient`.
     *
     * Returns a boolean value indicating whether the operation succeeded.
     *
     * Emits a {T [...]

2021-08-16 22:39 UTC, Grafskiy98 approved these changes, later dismissed

2021-08-19 17:26 UTC, ramyaparimi approved these changes
@thispsj Thanks a bunch for your time and effort make these changes. The information is quite detailed. I have a couple of minor edits and the changes are good to go.  I'll update the branch and get this merged once tests are passed 🍏

2021-08-19 17:48 UTC, ramyaparimi requested changes
@thispsj We realized we cannot make changes to this file. Could go ahead and make the changes suggested so this can be approved and merged ✨ 

Can you also enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks so much for taking your time and effort to help fill this gap in the documentation 💖. We are overjoyed by the help we've been receiving from your contributions ✨.

2021-08-20 05:27 UTC, thispsj commented
@ramyaparimi I'm adding in your suggestions.

2021-08-20 05:53 UTC, thispsj commented
One more thing @ramyaparimi , you changed the link in the issue,pr & comments column of the table to a raw link. But such raw links don't work on private repos without a token query parameter which is attached by GitHub automatically. But if you use the `raw` query flag using a relative link then the token doesn't appear because GitHub automatically parses it while loading the image.

Please share your opinion on this.

2021-08-20 13:42 UTC, ramyaparimi commented
> One more thing @ramyaparimi , you changed the link in the issue,pr & comments column of the table to a raw link. But such raw links don't work on private repos without a token query parameter which is attached by GitHub automatically when you press Download button. But if you use the `raw` query flag using a relative link then the token doesn't appear because GitHub automatically parses it while loading the image.
> 
> Please share your opinion on this.

Ah! I see what you mean!! Thank you for the clarification 🐢 Yes, you are correct, such link from a private repository doesn't work in a public repository. Could you revert back that change?? We will be good to merge once that is done ✨

2021-08-20 13:46 UTC, ramyaparimi requested changes
Could revert the change made for link used for image in issue, pr comments?

2021-08-20 13:48 UTC, thispsj commented
Yes doing that rn

2021-08-20 13:59 UTC, thispsj commented
@ramyaparimi should I also remove that **In a `.md` file on another repo** row from the table ?

2021-08-20 14:12 UTC, ramyaparimi commented
> @ramyaparimi should I also remove that **In a `.md` file on another repo** row from the table ?

That can stay! I checked that and it works 👍

2021-08-20 14:25 UTC, thispsj commented
@ramyaparimi done :+1:

2021-08-20 15:55 UTC, ramyaparimi requested changes
@thispsj I suggested couple changes for the content to reflect the modifications we made. It should be good once those changes are made 👍

2021-08-20 15:55 UTC, ramyaparimi commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +When displaying an image from a different repository, obtain the raw link of the image from the **Download** page for the image.
```suggestion

```

2021-08-20 15:55 UTC, ramyaparimi commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +When displaying an image from a different repository, obtain the raw link of the image from the **Download** page for the image.
This line can be removed!

2021-08-20 15:55 UTC, ramyaparimi commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +For example, if you want to use an image that is in the same repository as your `.md` file, you can use a relative link for the image. If you want to display the same image in an issue, pull request,
```suggestion
For example, if you want to use an image that is in the same repository as your `.md` file, you can use a relative link for the image. 
```

2021-08-20 15:55 UTC, ramyaparimi commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +For example, if you want to use an image that is in the same repository as your `.md` file, you can use a relative link for the image. If you want to display the same image in an issue, pull request,
This can get confusing now, so we can delete that sentence.

2021-08-21 02:13 UTC, ramyaparimi requested changes

2021-08-21 02:13 UTC, ramyaparimi commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +For example, if you want to use an image that is in the same repository as your `.md` file, you can use a relative link for the image.
```suggestion
Here are some examples for using relative links to display an image in a `.md` file.
```

2021-08-21 06:01 UTC, thispsj commented
@ramyaparimi done.

2021-08-23 06:24 UTC, Ghostcell3 commented
Yo need help getting to Washington d.c I can fix our national debt. I can fix our energy problems. I can fix our economy. I can solve global warming.

2021-08-23 12:54 UTC, felicitymay reviewed
This is looking great 💖 
I've suggested changes to tidy up the spacing in the table and expand "&" and "repo" to the full words. Otherwise, this looks ready to merge now. Thanks for your patience.

2021-08-23 12:54 UTC, felicitymay commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +| In Issues,Pull Requests & comments on another repo | `../../../github/docs/blob/main/assets/images/electrocat.png?raw=true` |
Fixing the spaces and captialization:

```suggestion
| In issues, pull requests, and comments on another repository | `../../../github/docs/blob/main/assets/images/electrocat.png?raw=true` |
```

2021-08-23 12:54 UTC, felicitymay commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +| In Issues,Pull Requests & comments of the repository | `../blob/main/assets/images/electrocat.png` |
```suggestion
| In issues, pull requests, and comments in the repository | `../blob/main/assets/images/electrocat.png` |
```

2021-08-23 12:54 UTC, felicitymay commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +| In a `.md` file on another repo | `/../../../../github/docs/blob/main/assets/images/electrocat.png` |
```suggestion
| In a `.md` file in another repository | `/../../../../github/docs/blob/main/assets/images/electrocat.png` |
```

2021-08-23 12:54 UTC, felicitymay commented on content/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.md
> +**Note**: The last two relative links in the table above will work across private repos only if the viewer has at least read access to the private repo.
```suggestion
**Note**: The last two relative links in the table above will work for images in private repositories only if the viewer has at least read access to the private repository.
```

2021-08-23 14:24 UTC, felicitymay approved these changes
@thispsj - thanks for the further updates.

This looks ready to merge 💖

2021-08-23 14:30 UTC, ramyaparimi approved these changes
@thispsj Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏 

Thanks a bunch for contributing to the GitHub docs ✨ Your efforts, patience and time are greatly appreciated 🐬

2021-08-23 14:31 UTC, ramyaparimi commented
@thispsj Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in 😄. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2021-08-23 14:34 UTC, thispsj commented
@ramyaparimi done.

P.S: You don't need to press the Update Branch button. (My action does that automatically whenever Octomerger or someone else pushes to main)

2021-08-23 15:23 UTC, merged