Update generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md
github/docs pull request #908
Opened 2020-10-29 16:25 UTC by poonam-lamba

I ran the steps today on mac OS Catalina and it did not work for me. I had to make two changes that I updated in the doc.

### Why:

### What's being changed:

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2020-11-02 21:56 UTC, janiceilene commented
Thanks for opening a pull request @poonam-lamba! I'll get this triaged for review ✨

2020-11-04 14:16 UTC, hubwriter commented on content/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md
> +  {% endnote %}
To render correctly, the note box needs a blank line above the opening tag, and more indentation. See [the staging deployment](https://docs-908--patch-1.herokuapp.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent). I'd also suggest simplifying the advice about `UseKeychain`:
 
```suggestion

     {% note %}

     **Note:** If you chose not to add a passphrase to your key, you should omit the `UseKeychain` line.
  
     {% endnote %}
```

2020-11-04 14:18 UTC, hubwriter commented on content/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md
> +  **Note:** The `-K` option is Apple's standard version of `ssh-add`, which stores the passphrase in your keychain for you when you add an ssh key to the ssh-agent.If you leave your passphrase blank,
```suggestion
  **Note:** The `-K` option is Apple's standard version of `ssh-add`, which stores the passphrase in your keychain for you when you add an ssh key to the ssh-agent. If you chose not to add a passphrase to your key, run the command without the `-K` option. 
```

2020-11-04 14:20 UTC, hubwriter requested changes
@poonam-lamba - Many thanks for creating this pull request. Although we direct people to use a passphrase I think it's helpful to provide this extra information for people who use a key without a passphrase.

I've suggested a few small changes.

Thanks again for helping to improve GitHub documentation. 👍

2020-11-11 20:23 UTC, hubwriter approved these changes

2020-11-20 09:11 UTC, hubwriter commented
No response from author to my commit here
https://github.com/github/docs/pull/908/commits/7566ecb23ca95cdf827896831a9ce7196e57d23e
so I'm going to assume all is good here and merge this now.

2020-11-20 09:11 UTC, hubwriter approved these changes

2020-11-20 09:25 UTC, merged