Document behavior in case of suspension by owner.
github/docs pull request #9477
Opened 2021-09-01 12:44 UTC by Zimmi48

### Why:

Document what I learned about GitHub App suspension by asking GitHub support (ticket `#1291684`).

### What's being changed:

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

2021-09-01 15:12 UTC, TorrZeed reviewed
Duplicate of #

2021-09-01 15:24 UTC, Zimmi48 commented
@TorrZeed duplicate of which PR?

2021-09-02 12:12 UTC, ramyaparimi requested changes
@Zimmi48 I made a suggestion as per the format we use for calling out `note`. For more information see "[Callout tags](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#usage)".

2021-09-02 12:12 UTC, ramyaparimi commented on content/developers/apps/managing-github-apps/suspending-a-github-app-installation.md
> +
```suggestion
{% note %}

**Note:** If an installation has been suspended by the GitHub App owner, then the option to unsuspend the installation is removed from the installation owner's app's settings and thus they will not be able to unsuspend it on their own. They can still change other settings (e.g., repository selection) while the app is suspended.

{% endnote %}
```

2021-09-02 12:15 UTC, ramyaparimi commented
@Zimmi48 
Thanks so much for opening a PR! I got this triaged for a writer's review :zap:

2021-09-03 12:22 UTC, ramyaparimi requested changes, later dismissed
@Zimmi48 I saw this at staging and looks like it needs spacing. Could you add these changes?? ✨

2021-09-03 12:22 UTC, ramyaparimi commented on content/developers/apps/managing-github-apps/suspending-a-github-app-installation.md
>  {% data reusables.user-settings.access_settings %}
```suggestion

{% endnote %}

{% data reusables.user-settings.access_settings %}
```

2021-09-03 12:55 UTC, Zimmi48 commented
Looks better now. Thanks @ramyaparimi!

2021-09-09 18:25 UTC, lecoursen reviewed
Thanks for adding this useful information! I'm going to apply a small suggestion and then merge. ⚡

2021-09-09 18:25 UTC, lecoursen commented on content/developers/apps/managing-github-apps/suspending-a-github-app-installation.md
> +{% endnote %}
This is general information that doesn't meet [our criteria for a callout](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#callouts). 

```suggestion
If an installation has been suspended by the {% data variables.product.prodname_github_app %} owner, installation owners cannot unsuspend their installations of the {% data variables.product.prodname_github_app %}. However, installation owners can change other settings, such as repository selection, while the app is suspended.
```

2021-09-09 18:27 UTC, lecoursen approved these changes

2021-09-09 18:37 UTC, merged